export interface Product {
  id: number
  name: string
  brand: string
  category: string
  price: number
  mrp: number
  rating: number
  reviews: number
  image: string
  badge?: string
  badgeBg?: string
  shortDesc: string
  description: string
  howToUse: string
  ingredients: string[]
  keyIngredients: { name: string; benefit: string; icon: string }[]
  benefits: string[]
  skinTypes: string[]
  concerns: string[]
  size: string
  inStock: boolean
  tags: string[]
  mainCategory?: string
}

export const ALL_PRODUCTS: Product[] = [
  // ── SKINCARE (existing, mainCategory: 'skincare') ───────────────────────
  {
    id: 1,
    name: 'Vitamin C 15% Brightening Serum',
    brand: 'DermIQ',
    category: 'Serum',
    price: 799,
    mrp: 1299,
    rating: 4.9,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    badge: 'Bestseller',
    badgeBg: '#1A2E2B',
    shortDesc: 'Clinical-grade Vitamin C with ferulic acid for visible brightening in 2 weeks.',
    description: 'Our most-loved serum powered by 15% stable Vitamin C (Ascorbic Acid) combined with Ferulic Acid and Vitamin E. This potent antioxidant trio protects skin from free radical damage, visibly fades dark spots, and delivers a natural glow. Lightweight, fast-absorbing formula that works on all skin types without irritation.',
    howToUse: 'Apply 3-4 drops to clean, dry face every morning. Gently pat in. Follow with moisturiser and SPF 50+. Avoid eye area. Start with every other day if new to Vitamin C.',
    ingredients: ['Ascorbic Acid 15%', 'Ferulic Acid 0.5%', 'Tocopherol (Vitamin E)', 'Sodium Hyaluronate', 'Niacinamide 3%', 'Panthenol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Vitamin C 15%', benefit: 'Brightens skin, fades dark spots, boosts collagen', icon: '🍊' },
      { name: 'Ferulic Acid', benefit: 'Stabilises Vitamin C, doubles antioxidant protection', icon: '🌾' },
      { name: 'Vitamin E', benefit: 'Nourishes and protects skin barrier', icon: '💛' },
      { name: 'Hyaluronic Acid', benefit: 'Provides hydration and plumping effect', icon: '💧' },
    ],
    benefits: ['Visibly brightens dull skin in 14 days', 'Fades dark spots and hyperpigmentation', 'Boosts natural collagen production', 'Protects against UV and pollution damage', 'Evens out skin tone'],
    skinTypes: ['Oily', 'Combination', 'Normal', 'Dry'],
    concerns: ['Dark spots', 'Dull skin', 'Uneven tone', 'Anti-aging'],
    size: '30ml',
    inStock: true,
    tags: ['brightening', 'vitamin-c', 'antioxidant', 'morning'],
    mainCategory: 'skincare',
  },
  {
    id: 2,
    name: 'Hyaluronic Acid 2% + B5 Deep Hydra Gel',
    brand: 'DermIQ',
    category: 'Moisturiser',
    price: 649,
    mrp: 999,
    rating: 4.8,
    reviews: 1876,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Multi-molecular hyaluronic acid gel that locks in 72-hour hydration.',
    description: 'A lightweight gel moisturiser containing three molecular weights of Hyaluronic Acid to hydrate skin at every layer. Combined with Vitamin B5 (Panthenol) for barrier repair, this formula delivers intense hydration without any greasy residue. Perfect for oily and combination skin types.',
    howToUse: 'Apply a pea-sized amount to clean face morning and night. Can be used over serums. Suitable as the final step in AM routine before SPF.',
    ingredients: ['Sodium Hyaluronate (Low, Medium, High MW)', 'Panthenol (B5)', 'Sodium PCA', 'Allantoin', 'Centella Asiatica Extract', 'Glycerin', 'Carbomer', 'Aqua'],
    keyIngredients: [
      { name: 'Hyaluronic Acid (3 weights)', benefit: 'Hydrates all skin layers, plumps fine lines', icon: '💧' },
      { name: 'Vitamin B5', benefit: 'Repairs skin barrier, soothes irritation', icon: '🛡️' },
      { name: 'Centella Asiatica', benefit: 'Calms redness and inflammation', icon: '🌿' },
      { name: 'Allantoin', benefit: 'Smoothens and conditions skin texture', icon: '✨' },
    ],
    benefits: ['72-hour lasting hydration', 'Non-greasy lightweight formula', 'Repairs damaged skin barrier', 'Calms redness and sensitivity', 'Plumps fine lines'],
    skinTypes: ['Oily', 'Combination', 'Normal', 'Sensitive'],
    concerns: ['Dehydration', 'Dullness', 'Sensitivity', 'Fine lines'],
    size: '50ml',
    inStock: true,
    tags: ['hydration', 'gel', 'hyaluronic-acid', 'lightweight'],
    mainCategory: 'skincare',
  },
  {
    id: 3,
    name: 'Mineral Sunscreen SPF 50+ PA++++',
    brand: 'DermIQ',
    category: 'Sunscreen',
    price: 549,
    mrp: 899,
    rating: 4.9,
    reviews: 3102,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&q=80',
    badge: 'SPF 50+',
    badgeBg: '#C8976A',
    shortDesc: 'Invisible mineral sunscreen with zero white cast. Dermatologist recommended.',
    description: 'India\'s first truly invisible mineral sunscreen. Formulated with micronized Zinc Oxide and Titanium Dioxide for broad-spectrum UVA/UVB protection. The PA++++ rating means superior protection against skin aging and darkening. Matte finish, no white cast, water-resistant up to 80 minutes.',
    howToUse: 'Apply generously as the last step of your AM skincare routine. Use 1/4 teaspoon for the face alone. Reapply every 2-3 hours when outdoors. Suitable for daily use.',
    ingredients: ['Zinc Oxide 10%', 'Titanium Dioxide 5%', 'Niacinamide 3%', 'Tocopherol', 'Aloe Vera Extract', 'Dimethicone', 'Caprylic/Capric Triglyceride', 'Aqua'],
    keyIngredients: [
      { name: 'Zinc Oxide 10%', benefit: 'Broad-spectrum UVA/UVB protection', icon: '☀️' },
      { name: 'Titanium Dioxide 5%', benefit: 'Reflects harmful UV rays physically', icon: '🛡️' },
      { name: 'Niacinamide 3%', benefit: 'Minimises pores, controls oil', icon: '🔬' },
      { name: 'Aloe Vera', benefit: 'Soothes and hydrates skin', icon: '🌿' },
    ],
    benefits: ['SPF 50+ PA++++ broad-spectrum protection', 'Zero white cast on all skin tones', 'Matte finish controls oil', 'Water-resistant 80 minutes', 'Suitable for sensitive skin'],
    skinTypes: ['All skin types', 'Sensitive', 'Oily', 'Acne-prone'],
    concerns: ['Sun damage', 'Tanning', 'Premature aging', 'Hyperpigmentation'],
    size: '50g',
    inStock: true,
    tags: ['sunscreen', 'spf50', 'mineral', 'matte', 'daily-protection'],
    mainCategory: 'skincare',
  },
  {
    id: 4,
    name: 'Gentle Amino Acid Foaming Wash',
    brand: 'DermIQ',
    category: 'Cleanser',
    price: 399,
    mrp: 599,
    rating: 4.7,
    reviews: 1543,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&q=80',
    shortDesc: 'pH-balanced amino acid cleanser that cleans without stripping skin\'s natural oils.',
    description: 'A gentle yet effective face wash powered by amino acid-based surfactants — the same building blocks as your skin. Maintains your skin\'s natural pH of 5.5, ensuring the microbiome stays healthy. Creates a soft, creamy lather that removes makeup, sunscreen, and impurities without leaving skin tight or dry.',
    howToUse: 'Wet face with lukewarm water. Apply a small amount to palms, lather, and massage gently onto face in circular motions for 60 seconds. Rinse thoroughly. Use morning and night.',
    ingredients: ['Sodium Cocoyl Glutamate', 'Disodium Cocoyl Glutamate', 'Glycerin', 'Panthenol', 'Allantoin', 'Ceramide NP', 'Niacinamide 2%', 'Citric Acid', 'Aqua'],
    keyIngredients: [
      { name: 'Amino Acid Surfactants', benefit: 'Cleans gently without disrupting pH', icon: '🫧' },
      { name: 'Ceramide NP', benefit: 'Maintains and strengthens skin barrier', icon: '🛡️' },
      { name: 'Panthenol', benefit: 'Conditions and soothes skin post-cleanse', icon: '💚' },
      { name: 'Glycerin', benefit: 'Keeps skin hydrated even after washing', icon: '💧' },
    ],
    benefits: ['Maintains skin\'s natural pH 5.5', 'Removes impurities without over-cleansing', 'Leaves skin soft, not tight', 'Suitable for daily double cleanse', 'Safe for sensitive and acne-prone skin'],
    skinTypes: ['All skin types', 'Sensitive', 'Dry', 'Acne-prone'],
    concerns: ['Sensitivity', 'Dryness post-cleanse', 'Barrier damage'],
    size: '150ml',
    inStock: true,
    tags: ['cleanser', 'gentle', 'amino-acid', 'ph-balanced', 'daily'],
    mainCategory: 'skincare',
  },
  {
    id: 5,
    name: 'Retinol 0.2% Night Renewal Serum',
    brand: 'Minimalist',
    category: 'Serum',
    price: 699,
    mrp: 999,
    rating: 4.6,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1611080541599-8c6dbde6ed28?w=600&h=600&fit=crop&q=80',
    badge: 'Derma Pick',
    badgeBg: '#2D5F5A',
    shortDesc: 'Beginner-friendly retinol formula encapsulated for zero irritation.',
    description: 'Science-backed retinol serum with 0.2% encapsulated retinol for gradual, controlled release throughout the night. Unlike traditional retinol, our microencapsulated formula minimises irritation, redness, and peeling — perfect for retinol beginners. Contains squalane and peptides to support skin while retinol works.',
    howToUse: 'Use only at night. Apply 3-4 drops after cleansing and toning. Start with 2-3 times a week and gradually increase. Always follow with moisturiser. Use SPF 50+ during the day. Avoid mixing with AHA/BHA on the same night.',
    ingredients: ['Encapsulated Retinol 0.2%', 'Squalane', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Sodium Hyaluronate', 'Niacinamide 2%', 'Tocopherol', 'Aqua'],
    keyIngredients: [
      { name: 'Encapsulated Retinol 0.2%', benefit: 'Renews skin cells, reduces wrinkles and dark spots', icon: '🌙' },
      { name: 'Squalane', benefit: 'Locks in moisture, prevents retinol dryness', icon: '💧' },
      { name: 'Peptides', benefit: 'Boosts collagen, firms and tightens skin', icon: '🧬' },
      { name: 'Niacinamide', benefit: 'Reduces redness from retinol use', icon: '🔬' },
    ],
    benefits: ['Reduces fine lines and wrinkles in 8 weeks', 'Fades acne scars and dark spots', 'Improves skin texture and tone', 'Boosts collagen production', 'Minimal irritation with encapsulation technology'],
    skinTypes: ['Normal', 'Combination', 'Oily'],
    concerns: ['Anti-aging', 'Acne scars', 'Uneven texture', 'Fine lines'],
    size: '30ml',
    inStock: true,
    tags: ['retinol', 'anti-aging', 'night-serum', 'minimalist'],
    mainCategory: 'skincare',
  },
  {
    id: 6,
    name: 'Ceramide + Hyaluronic Barrier Cream',
    brand: 'DermIQ',
    category: 'Moisturiser',
    price: 849,
    mrp: 1299,
    rating: 4.8,
    reviews: 2103,
    image: 'https://images.unsplash.com/photo-1583248369069-9d91f1640fe6?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Ceramide-rich barrier repair cream for dry, sensitive, and compromised skin.',
    description: 'Clinically formulated with 3 essential ceramides (NP, AP, EOP), cholesterol, and fatty acids in the same ratio found in healthy skin. This barrier-restoring moisturiser is fragrance-free, suitable for eczema-prone skin, and rebuilds the protective layer that keeps moisture in and irritants out.',
    howToUse: 'Apply a generous layer to face and neck morning and night. Can be used on body too. For best results, apply immediately after washing while skin is still slightly damp.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Cholesterol', 'Fatty Acids', 'Sodium Hyaluronate', 'Glycerin', 'Dimethicone', 'Tocopherol', 'Aqua'],
    keyIngredients: [
      { name: 'Ceramides NP+AP+EOP', benefit: 'Rebuilds and strengthens skin barrier', icon: '🏺' },
      { name: 'Cholesterol', benefit: 'Restores lipid balance in skin', icon: '⚖️' },
      { name: 'Hyaluronic Acid', benefit: 'Intense 48-hour hydration', icon: '💧' },
      { name: 'Dimethicone', benefit: 'Creates protective skin film', icon: '🛡️' },
    ],
    benefits: ['Repairs damaged skin barrier', 'Relieves dry and flaky skin', 'Suitable for eczema-prone skin', 'Fragrance-free and hypoallergenic', 'Locks in moisture for 48 hours'],
    skinTypes: ['Dry', 'Sensitive', 'Normal', 'Eczema-prone'],
    concerns: ['Dryness', 'Barrier damage', 'Sensitivity', 'Eczema'],
    size: '60ml',
    inStock: true,
    tags: ['ceramide', 'barrier-repair', 'dry-skin', 'sensitive'],
    mainCategory: 'skincare',
  },
  {
    id: 7,
    name: 'Niacinamide 10% + Zinc 1% Serum',
    brand: 'Minimalist',
    category: 'Serum',
    price: 449,
    mrp: 699,
    rating: 4.7,
    reviews: 4320,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop&q=80',
    badge: 'Top Rated',
    badgeBg: '#2D5F5A',
    shortDesc: 'India\'s #1 niacinamide serum. Minimises pores and controls oiliness in 4 weeks.',
    description: 'The most straightforward pore-minimising serum available. 10% Niacinamide (Vitamin B3) combined with 1% Zinc PCA reduces the appearance of enlarged pores, balances sebum production, and fades blemishes. A cult favourite backed by 4000+ verified reviews.',
    howToUse: 'Apply 3-4 drops to clean skin, morning and night. Can be mixed with moisturiser. Avoid using with pure Vitamin C on the same step — use them at different times of day.',
    ingredients: ['Niacinamide 10%', 'Zinc PCA 1%', 'Sodium Hyaluronate', 'Panthenol', 'Tamarind Seed Extract', 'Pentylene Glycol', 'Aqua'],
    keyIngredients: [
      { name: 'Niacinamide 10%', benefit: 'Minimises pores, fades dark spots, reduces redness', icon: '🔬' },
      { name: 'Zinc PCA 1%', benefit: 'Controls sebum, prevents breakouts', icon: '⚡' },
      { name: 'Tamarind Extract', benefit: 'Natural AHA for gentle exfoliation', icon: '🌿' },
    ],
    benefits: ['Visibly minimises pores in 4 weeks', 'Controls oiliness and shine', 'Fades post-acne marks', 'Reduces redness and blotchiness', 'Brightens overall complexion'],
    skinTypes: ['Oily', 'Combination', 'Acne-prone'],
    concerns: ['Large pores', 'Oiliness', 'Acne marks', 'Dull skin'],
    size: '30ml',
    inStock: true,
    tags: ['niacinamide', 'pores', 'oily-skin', 'minimalist', 'bestseller'],
    mainCategory: 'skincare',
  },
  {
    id: 8,
    name: 'Watermelon Glow Sleeping Mask',
    brand: 'Dot & Key',
    category: 'Treatment',
    price: 699,
    mrp: 999,
    rating: 4.8,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1600428863598-3ef3a8c50f90?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Overnight mask with real watermelon extract that wakes you up to glowing skin.',
    description: 'Wake up to visibly glowing, hydrated skin with this overnight treatment mask. Packed with real watermelon extract, hyaluronic acid, and vitamin C, this sleeping mask works while you sleep to replenish, hydrate, and brighten. Gel-cream texture absorbs quickly, leaving no sticky residue on pillows.',
    howToUse: 'Apply as the last step of your night skincare routine. Use 2-3 times a week. Apply a generous, even layer over entire face. Leave on overnight. Rinse in the morning with a gentle cleanser.',
    ingredients: ['Citrullus Lanatus (Watermelon) Fruit Extract 15%', 'Sodium Hyaluronate', 'Ascorbic Acid 3%', 'Niacinamide 2%', 'Aloe Vera Gel', 'Centella Asiatica', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Watermelon Extract 15%', benefit: 'Hydrates, soothes, and provides antioxidants', icon: '🍉' },
      { name: 'Vitamin C 3%', benefit: 'Brightens and evens skin tone overnight', icon: '✨' },
      { name: 'Hyaluronic Acid', benefit: 'Deep overnight hydration', icon: '💧' },
      { name: 'Centella Asiatica', benefit: 'Calms and repairs skin while sleeping', icon: '🌿' },
    ],
    benefits: ['Wake up with visibly glowing skin', 'Deep overnight hydration', 'Fades dark spots while you sleep', 'Gel texture doesn\'t transfer to pillows', 'Refreshes dull and tired skin'],
    skinTypes: ['Normal', 'Dry', 'Combination', 'Sensitive'],
    concerns: ['Dullness', 'Dehydration', 'Dark spots', 'Uneven tone'],
    size: '85g',
    inStock: true,
    tags: ['overnight-mask', 'sleeping-mask', 'glow', 'dot-and-key'],
    mainCategory: 'skincare',
  },
  {
    id: 9,
    name: 'SPF 50 Invisible Matte Sunscreen',
    brand: 'Pilgrim',
    category: 'Sunscreen',
    price: 599,
    mrp: 899,
    rating: 4.6,
    reviews: 2156,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Ultra-light Korean-formula SPF 50 sunscreen with zero white cast and matte finish.',
    description: 'Inspired by Korean skincare technology, this feather-light sunscreen provides SPF 50 PA++++ protection with an invisible, matte finish. Formulated with a hybrid of chemical and mineral filters, it protects against both UVA and UVB rays while keeping skin oil-free for up to 8 hours.',
    howToUse: 'Apply as last step of skincare. Use ¼ tsp for face. Reapply every 2-3 hours outdoors. Can be worn under makeup. Suitable for daily use.',
    ingredients: ['Homosalate 10%', 'Octisalate 5%', 'Zinc Oxide 3%', 'Niacinamide 3%', 'Silica', 'Glycerin', 'Dimethicone', 'Aqua'],
    keyIngredients: [
      { name: 'Hybrid UV Filters', benefit: 'Complete UVA + UVB protection', icon: '☀️' },
      { name: 'Niacinamide 3%', benefit: 'Controls oil and minimises pores', icon: '🔬' },
      { name: 'Silica', benefit: 'Mattifies skin for 8 hours', icon: '✨' },
    ],
    benefits: ['SPF 50 PA++++ protection', 'Matte finish lasts 8 hours', 'Makeup-friendly base', 'No white cast on deeper skin tones', 'Lightweight Korean formula'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    concerns: ['Sun protection', 'Oiliness', 'Tanning'],
    size: '50g',
    inStock: true,
    tags: ['sunscreen', 'spf50', 'matte', 'pilgrim', 'korean'],
    mainCategory: 'skincare',
  },
  {
    id: 10,
    name: 'Kojic Acid 2% + Alpha Arbutin Serum',
    brand: 'Plum',
    category: 'Serum',
    price: 549,
    mrp: 799,
    rating: 4.5,
    reviews: 1089,
    image: 'https://images.unsplash.com/photo-1631390009-90465ff72860?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Powerful dark spot corrector with Kojic Acid + Alpha Arbutin for visible results in 3 weeks.',
    description: 'Target stubborn dark spots, melasma, and post-inflammatory hyperpigmentation with this dual-action brightening serum. Kojic Acid inhibits melanin production while Alpha Arbutin gently exfoliates discoloured cells. Results visible in as little as 3 weeks with consistent use.',
    howToUse: 'Apply 3-4 drops to targeted areas (dark spots, melasma patches) or entire face. Use at night. Follow with moisturiser. Wear SPF every morning when using this product.',
    ingredients: ['Kojic Acid 2%', 'Alpha Arbutin 1%', 'Niacinamide 5%', 'Sodium Hyaluronate', 'Vitamin C 3%', 'Panthenol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Kojic Acid 2%', benefit: 'Inhibits melanin for visible spot reduction', icon: '✨' },
      { name: 'Alpha Arbutin 1%', benefit: 'Gently removes discoloured skin cells', icon: '🌸' },
      { name: 'Niacinamide 5%', benefit: 'Reduces inflammation and redness', icon: '🔬' },
    ],
    benefits: ['Fades dark spots in 3 weeks', 'Treats melasma and sun spots', 'Reduces post-acne marks', 'Brightens overall complexion', 'Gentle enough for sensitive skin'],
    skinTypes: ['All skin types'],
    concerns: ['Dark spots', 'Melasma', 'Hyperpigmentation', 'Post-acne marks'],
    size: '30ml',
    inStock: true,
    tags: ['dark-spots', 'kojic-acid', 'brightening', 'plum'],
    mainCategory: 'skincare',
  },
  {
    id: 11,
    name: 'Peptide Complex Eye Cream',
    brand: 'DermIQ',
    category: 'Treatment',
    price: 999,
    mrp: 1499,
    rating: 4.9,
    reviews: 487,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&h=600&fit=crop&q=80',
    badge: 'Premium',
    badgeBg: '#3D7A74',
    shortDesc: 'Clinical-strength peptide eye cream. Reduces dark circles and crow\'s feet in 4 weeks.',
    description: 'Our most advanced eye treatment featuring 5 targeted peptides proven to reduce the appearance of crow\'s feet, puffiness, and dark circles. The caffeine complex constricts blood vessels to reduce under-eye bags, while ceramides prevent moisture loss around the delicate eye area.',
    howToUse: 'Use morning and night. Apply a small amount (rice grain size) with ring finger to orbital bone area. Pat gently, do not rub. Use consistently for 4+ weeks for best results.',
    ingredients: ['Argireline (Acetyl Hexapeptide-3) 5%', 'Leuphasyl 3%', 'Caffeine 2%', 'Ceramide NP', 'Sodium Hyaluronate', 'Palmitoyl Tripeptide-1', 'Niacinamide', 'Shea Butter', 'Aqua'],
    keyIngredients: [
      { name: 'Argireline 5%', benefit: 'Relaxes expression lines, reduces crow\'s feet', icon: '👁️' },
      { name: 'Caffeine 2%', benefit: 'Reduces puffiness and dark circles', icon: '☕' },
      { name: 'Ceramides', benefit: 'Strengthens delicate eye area barrier', icon: '🛡️' },
      { name: 'Peptide Complex', benefit: 'Firms and tightens under-eye skin', icon: '🧬' },
    ],
    benefits: ['Reduces crow\'s feet in 4 weeks', 'Minimises dark circles and puffiness', 'Hydrates delicate eye area', 'Firms under-eye skin', 'Safe for contact lens wearers'],
    skinTypes: ['All skin types'],
    concerns: ['Dark circles', 'Puffiness', 'Crow\'s feet', 'Eye area aging'],
    size: '15ml',
    inStock: true,
    tags: ['eye-cream', 'peptides', 'dark-circles', 'anti-aging', 'premium'],
    mainCategory: 'skincare',
  },
  {
    id: 12,
    name: 'AHA 25% + BHA 2% Peeling Solution',
    brand: 'Minimalist',
    category: 'Treatment',
    price: 549,
    mrp: 799,
    rating: 4.7,
    reviews: 3654,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&h=600&fit=crop&q=80',
    badge: 'Trending',
    badgeBg: '#C8976A',
    shortDesc: '10-minute at-home peel for smooth, glowing skin. Clinically tested formulation.',
    description: 'A powerful chemical exfoliating solution combining 25% AHA (Glycolic, Lactic, Tartaric acids) and 2% BHA (Salicylic Acid) for a complete surface and pore-deep exfoliation. Works in just 10 minutes to dissolve dead skin, unclog pores, and reveal brighter, smoother skin underneath.',
    howToUse: 'PATCH TEST FIRST. Use once weekly. Apply to dry face, avoiding eye and lip area. Leave on for maximum 10 minutes. Rinse thoroughly. Do not use on irritated skin. Always use SPF the next day. Not suitable for beginners.',
    ingredients: ['Glycolic Acid 10%', 'Lactic Acid 10%', 'Tartaric Acid 5%', 'Citric Acid 0.5%', 'Salicylic Acid 2%', 'Sodium Hyaluronate', 'Aloe Vera', 'Aqua'],
    keyIngredients: [
      { name: 'AHA Complex 25%', benefit: 'Exfoliates surface dead skin, improves texture', icon: '⚗️' },
      { name: 'BHA (Salicylic Acid) 2%', benefit: 'Unclogs pores, treats blackheads', icon: '🔬' },
      { name: 'Hyaluronic Acid', benefit: 'Prevents over-drying during peel', icon: '💧' },
    ],
    benefits: ['Smoothens skin texture in 1 use', 'Unclogs pores and removes blackheads', 'Fades acne scars and dark spots', 'Brightens dull, tired skin', 'Clinically proven formulation'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    concerns: ['Rough texture', 'Blackheads', 'Acne scars', 'Dullness'],
    size: '30ml',
    inStock: true,
    tags: ['aha', 'bha', 'peeling', 'exfoliant', 'minimalist', 'advanced'],
    mainCategory: 'skincare',
  },
  {
    id: 13,
    name: 'Salicylic Acid 2% Face Wash',
    brand: 'Minimalist',
    category: 'Cleanser',
    price: 299,
    mrp: 499,
    rating: 4.6,
    reviews: 5621,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=600&fit=crop&q=80',
    shortDesc: 'BHA face wash that clears breakouts and minimises pores with every wash.',
    description: 'A gentle, daily-use face wash with 2% Salicylic Acid (BHA) that penetrates deep into pores to remove excess oil, dead skin, and blackheads. Unlike harsh acne washes, this formula maintains skin\'s pH balance and includes soothing ingredients to prevent over-drying.',
    howToUse: 'Wet face. Apply and lather for 60 seconds. Focus on oily T-zone. Rinse with lukewarm water. Use morning and night for best results.',
    ingredients: ['Salicylic Acid 2%', 'Glycerin', 'Niacinamide 2%', 'Allantoin', 'Panthenol', 'Tea Tree Oil 0.5%', 'Sodium Laureth Sulfate', 'Aqua'],
    keyIngredients: [
      { name: 'Salicylic Acid 2%', benefit: 'Exfoliates inside pores, prevents breakouts', icon: '🧪' },
      { name: 'Tea Tree Oil', benefit: 'Antibacterial, targets acne bacteria', icon: '🌿' },
      { name: 'Niacinamide', benefit: 'Reduces post-acne redness', icon: '🔬' },
    ],
    benefits: ['Clears active breakouts', 'Unclogs and minimises pores', 'Reduces oiliness', 'Prevents future breakouts', 'Suitable for daily use'],
    skinTypes: ['Oily', 'Combination', 'Acne-prone'],
    concerns: ['Acne', 'Blackheads', 'Large pores', 'Oiliness'],
    size: '100ml',
    inStock: true,
    tags: ['acne', 'salicylic-acid', 'face-wash', 'minimalist', 'budget'],
    mainCategory: 'skincare',
  },
  {
    id: 14,
    name: 'Skin Brightening Kit (4 Products)',
    brand: 'DermIQ',
    category: 'Kit',
    price: 1999,
    mrp: 3296,
    rating: 4.9,
    reviews: 834,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop&q=80',
    badge: 'Save 39%',
    badgeBg: '#2D5F5A',
    shortDesc: 'Complete brightening routine: Vitamin C Serum + Niacinamide Serum + Moisturiser + SPF 50.',
    description: 'Our bestselling 4-step brightening routine curated by dermatologists. Get the Vitamin C 15% Brightening Serum, Niacinamide 10% Serum, Hyaluronic Acid Moisturiser, and Mineral SPF 50+ — everything you need for visibly brighter skin in 30 days. Save 39% vs buying individually.',
    howToUse: 'AM: Cleanse → Niacinamide Serum → Moisturiser → SPF 50. PM: Cleanse → Vitamin C Serum → Moisturiser. Use consistently for 30 days for best results.',
    ingredients: ['See individual products'],
    keyIngredients: [
      { name: 'Vitamin C 15%', benefit: 'Brightens and fades dark spots', icon: '🍊' },
      { name: 'Niacinamide 10%', benefit: 'Minimises pores, controls oil', icon: '🔬' },
      { name: 'SPF 50+ PA++++', benefit: 'Protects brightening results from UV', icon: '☀️' },
      { name: 'Hyaluronic Acid', benefit: 'Keeps skin hydrated and plump', icon: '💧' },
    ],
    benefits: ['Complete 4-step brightening routine', 'Save 39% vs buying individually', 'Dermatologist curated combination', 'Results in 30 days', 'Perfect gift for skincare lovers'],
    skinTypes: ['All skin types'],
    concerns: ['Dull skin', 'Dark spots', 'Uneven tone', 'General skincare'],
    size: '4-piece kit',
    inStock: true,
    tags: ['kit', 'brightening', 'gift', 'bundle', 'value'],
    mainCategory: 'skincare',
  },

  // ── BODYCARE (IDs 50–54) ────────────────────────────────────────────────
  {
    id: 50,
    name: 'Shea & Oat Deep Nourishing Body Lotion',
    brand: 'DermIQ',
    category: 'Body Lotion',
    price: 449,
    mrp: 699,
    rating: 4.7,
    reviews: 1102,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&q=80',
    badge: 'Bestseller',
    badgeBg: '#C8976A',
    shortDesc: 'Rich shea butter and colloidal oat lotion for deeply nourished, soft skin all day.',
    description: 'Indulge your skin with this velvety body lotion powered by Shea Butter, Colloidal Oat, and Ceramides. Clinically tested to provide 24-hour moisturisation, it soothes dry, itchy skin and restores suppleness. Non-greasy formula absorbs in seconds, leaving behind a subtle floral scent.',
    howToUse: 'Apply liberally to clean, dry skin after bathing. Massage gently in circular motions until fully absorbed. Use daily for best results. Pay extra attention to elbows, knees, and heels.',
    ingredients: ['Butyrospermum Parkii (Shea Butter)', 'Colloidal Oatmeal', 'Ceramide NP', 'Glycerin', 'Dimethicone', 'Tocopherol', 'Aloe Vera Extract', 'Aqua'],
    keyIngredients: [
      { name: 'Shea Butter', benefit: 'Deep nourishment and sealing moisture', icon: '🧈' },
      { name: 'Colloidal Oat', benefit: 'Soothes dryness and relieves itch', icon: '🌾' },
      { name: 'Ceramides', benefit: 'Restores skin barrier function', icon: '🛡️' },
    ],
    benefits: ['24-hour moisturisation', 'Soothes dry and itchy skin', 'Non-greasy fast-absorbing', 'Restores soft, supple skin', 'Suitable for sensitive skin'],
    skinTypes: ['Dry', 'Normal', 'Sensitive'],
    concerns: ['Dryness', 'Roughness', 'Sensitivity'],
    size: '250ml',
    inStock: true,
    tags: ['body-lotion', 'shea-butter', 'bodycare', 'moisturising'],
    mainCategory: 'bodycare',
  },
  {
    id: 51,
    name: 'Coffee & Brown Sugar Body Scrub',
    brand: 'Plum',
    category: 'Body Scrub',
    price: 349,
    mrp: 549,
    rating: 4.6,
    reviews: 876,
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#C8976A',
    shortDesc: 'Exfoliating coffee and brown sugar scrub that smoothens, de-tans, and energises skin.',
    description: 'Wake your skin up with this invigorating body scrub. Finely ground coffee granules combined with brown sugar gently buff away dead skin cells, while cold-pressed coconut oil moisturises as you scrub. The natural caffeine in coffee helps reduce the appearance of cellulite and uneven skin tone on the body.',
    howToUse: 'Apply a generous scoop to wet skin. Massage in circular motions for 2-3 minutes. Focus on rough areas like knees, elbows, and feet. Rinse thoroughly. Use 2-3 times a week. Follow with body lotion.',
    ingredients: ['Coffea Arabica (Coffee) Grounds', 'Brown Sugar', 'Cocos Nucifera (Coconut) Oil', 'Sweet Almond Oil', 'Glycerin', 'Vitamin E', 'Rosehip Oil', 'Natural Fragrance'],
    keyIngredients: [
      { name: 'Coffee Grounds', benefit: 'Exfoliates dead skin, reduces cellulite appearance', icon: '☕' },
      { name: 'Brown Sugar', benefit: 'Natural AHA for gentle chemical exfoliation', icon: '🍬' },
      { name: 'Coconut Oil', benefit: 'Deep moisturisation during scrubbing', icon: '🥥' },
    ],
    benefits: ['Removes dead skin cells', 'De-tans and brightens body skin', 'Reduces cellulite appearance', 'Moisturises while exfoliating', 'Invigorating energising scent'],
    skinTypes: ['All skin types'],
    concerns: ['Rough skin', 'Tanning', 'Dullness', 'Cellulite'],
    size: '200g',
    inStock: true,
    tags: ['body-scrub', 'coffee', 'exfoliating', 'bodycare'],
    mainCategory: 'bodycare',
  },
  {
    id: 52,
    name: 'Aloe & Mint Refreshing Body Wash',
    brand: 'DermIQ',
    category: 'Body Wash',
    price: 299,
    mrp: 449,
    rating: 4.5,
    reviews: 654,
    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Sulphate-free aloe vera and peppermint body wash that cleanses and refreshes without drying.',
    description: 'A gentle, sulphate-free body wash enriched with soothing Aloe Vera Gel and invigorating Peppermint Extract. This pH-balanced formula effectively removes dirt and sweat while preserving the skin\'s natural moisture barrier. Leaves skin feeling clean, fresh, and lightly hydrated.',
    howToUse: 'Apply to wet skin using a loofah or hands. Lather and massage gently. Rinse thoroughly. Use daily.',
    ingredients: ['Aloe Barbadensis (Aloe Vera) Gel', 'Mentha Piperita (Peppermint) Extract', 'Glycerin', 'Sodium Cocoyl Isethionate', 'Panthenol', 'Niacinamide 1%', 'Allantoin', 'Aqua'],
    keyIngredients: [
      { name: 'Aloe Vera', benefit: 'Soothes, hydrates, and heals skin', icon: '🌿' },
      { name: 'Peppermint Extract', benefit: 'Refreshes and energises with cooling sensation', icon: '🌱' },
      { name: 'Panthenol', benefit: 'Conditions and softens skin', icon: '💧' },
    ],
    benefits: ['Gentle sulphate-free cleansing', 'Refreshing cooling sensation', 'Preserves skin moisture', 'Daily-use suitable', 'pH-balanced formula'],
    skinTypes: ['All skin types'],
    concerns: ['Dryness', 'Body odour', 'Rough skin'],
    size: '300ml',
    inStock: true,
    tags: ['body-wash', 'aloe', 'sulphate-free', 'bodycare', 'daily'],
    mainCategory: 'bodycare',
  },
  {
    id: 53,
    name: 'Stretch Mark Repair Cream',
    brand: 'Mama Earth',
    category: 'Body Treatment',
    price: 599,
    mrp: 899,
    rating: 4.4,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&h=600&fit=crop&q=80',
    badge: 'Trending',
    badgeBg: '#C8976A',
    shortDesc: 'Clinically proven stretch mark cream with Centella, Retinol, and Hyaluronic Acid.',
    description: 'This dermatologist-formulated stretch mark repair cream helps fade existing stretch marks and prevent new ones from forming. The powerful combination of Centella Asiatica (Cica), Encapsulated Retinol, and Hyaluronic Acid boosts collagen synthesis, improves skin elasticity, and deeply hydrates for visible results in 8 weeks.',
    howToUse: 'Apply to affected areas (abdomen, thighs, hips, breasts) twice daily. Massage in circular upward motions until fully absorbed. Use consistently for minimum 8 weeks for visible results.',
    ingredients: ['Centella Asiatica Extract 5%', 'Encapsulated Retinol 0.1%', 'Sodium Hyaluronate', 'Shea Butter', 'Rosehip Oil', 'Peptides', 'Vitamin E', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Centella Asiatica 5%', benefit: 'Boosts collagen, improves skin elasticity', icon: '🌿' },
      { name: 'Encapsulated Retinol', benefit: 'Cell turnover for stretch mark reduction', icon: '✨' },
      { name: 'Hyaluronic Acid', benefit: 'Deep hydration, plumps and smoothens skin', icon: '💧' },
    ],
    benefits: ['Fades stretch marks in 8 weeks', 'Prevents new stretch marks', 'Improves skin elasticity', 'Deep long-lasting hydration', 'Suitable during and after pregnancy'],
    skinTypes: ['All skin types'],
    concerns: ['Stretch marks', 'Skin elasticity', 'Dryness'],
    size: '200ml',
    inStock: true,
    tags: ['stretch-marks', 'body-treatment', 'bodycare', 'pregnancy'],
    mainCategory: 'bodycare',
  },
  {
    id: 54,
    name: 'Whipped Cocoa Body Butter',
    brand: 'DermIQ',
    category: 'Body Butter',
    price: 499,
    mrp: 749,
    rating: 4.8,
    reviews: 789,
    image: 'https://images.unsplash.com/photo-1608248596854-f75a7b93ef5b?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Ultra-rich whipped cocoa and mango butter for intense overnight body nourishment.',
    description: 'An indulgent, whipped body butter blending Cocoa Butter, Mango Butter, and Sweet Almond Oil into a cloud-like texture. Perfect for extremely dry skin, this intensive treatment melts into skin and locks in moisture for up to 24 hours. Use as an overnight body mask or daily moisturiser for transformatively soft skin.',
    howToUse: 'Scoop a small amount and warm between palms. Apply to skin using long strokes. For intensive treatment, apply generously before bed and wear loose clothing overnight. Use daily on dry areas.',
    ingredients: ['Theobroma Cacao (Cocoa) Butter', 'Mangifera Indica (Mango) Seed Butter', 'Prunus Amygdalus Dulcis (Sweet Almond) Oil', 'Tocopherol', 'Shea Butter', 'Jojoba Oil', 'Vitamin C', 'Natural Fragrance'],
    keyIngredients: [
      { name: 'Cocoa Butter', benefit: 'Ultra-rich moisture seal for very dry skin', icon: '🍫' },
      { name: 'Mango Butter', benefit: 'Nourishes and smoothens rough skin patches', icon: '🥭' },
      { name: 'Sweet Almond Oil', benefit: 'Softens and improves skin tone', icon: '🌰' },
    ],
    benefits: ['24-hour intense moisture', 'Transforms extremely dry skin', 'Overnight body treatment', 'Softens rough patches', 'Rich chocolatey scent'],
    skinTypes: ['Dry', 'Very Dry'],
    concerns: ['Extreme dryness', 'Rough skin', 'Skin nourishment'],
    size: '150g',
    inStock: true,
    tags: ['body-butter', 'cocoa', 'intense-moisturising', 'bodycare'],
    mainCategory: 'bodycare',
  },

  // ── LIPS CARE (IDs 55–58) ──────────────────────────────────────────────
  {
    id: 55,
    name: 'SPF 30 Moisturising Lip Balm',
    brand: 'DermIQ',
    category: 'Lip Balm',
    price: 199,
    mrp: 299,
    rating: 4.8,
    reviews: 2145,
    image: 'https://images.unsplash.com/photo-1586495777744-4e6b0c8b9e0f?w=600&h=600&fit=crop&q=80',
    badge: 'Bestseller',
    badgeBg: '#C2185B',
    shortDesc: 'SPF 30 lip balm with ceramides and hyaluronic acid for sun-protected soft lips.',
    description: 'Your lips deserve UV protection too. This SPF 30 lip balm provides broad-spectrum sun protection while deeply moisturising with Ceramides, Hyaluronic Acid, and Shea Butter. Lightweight, non-sticky formula that can be worn alone or under lipstick. Suitable for daily use.',
    howToUse: 'Apply to lips before sun exposure. Reapply every 2 hours outdoors. Can be used throughout the day for ongoing moisture. Apply generously for best SPF efficacy.',
    ingredients: ['Zinc Oxide 8%', 'Sodium Hyaluronate', 'Ceramide NP', 'Butyrospermum Parkii (Shea Butter)', 'Beeswax', 'Sweet Almond Oil', 'Vitamin E', 'Natural Mango Flavour'],
    keyIngredients: [
      { name: 'Zinc Oxide SPF 30', benefit: 'Protects lips from UV damage and darkening', icon: '☀️' },
      { name: 'Hyaluronic Acid', benefit: 'Keeps lips plump and hydrated', icon: '💧' },
      { name: 'Ceramides', benefit: 'Repairs and strengthens lip barrier', icon: '🛡️' },
    ],
    benefits: ['SPF 30 sun protection', 'Prevents lip darkening from UV', 'Non-sticky moisture', 'Wear under any lipstick', 'Heals chapped lips'],
    skinTypes: ['All lip types'],
    concerns: ['Lip darkening', 'Chapped lips', 'Dryness'],
    size: '4g',
    inStock: true,
    tags: ['lip-balm', 'spf', 'lips-care', 'sun-protection'],
    mainCategory: 'lipscare',
  },
  {
    id: 56,
    name: 'Peptide Plumping Lip Serum',
    brand: 'DermIQ',
    category: 'Lip Serum',
    price: 699,
    mrp: 999,
    rating: 4.7,
    reviews: 567,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#C2185B',
    shortDesc: 'Peptide-rich lip serum that visibly plumps, smoothens lip lines, and boosts collagen.',
    description: 'Take your lip care to the next level with this targeted serum. Formulated with lip-plumping peptides, Hyaluronic Acid, and Vitamin C, this serum visibly reduces lip lines and vertical wrinkles around the mouth. Provides a subtle plumping effect without injections, and consistent use improves lip volume and definition.',
    howToUse: 'Apply 1-2 drops to clean lips morning and night. Gently massage into lips and lip line area. Follow with lip balm. Can be used alone or as a base under lip colour.',
    ingredients: ['Palmitoyl Tetrapeptide-7', 'Hyaluronic Acid', 'Ascorbic Acid 3%', 'Niacinamide', 'Panthenol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Lip Peptides', benefit: 'Plumps lips and reduces lip lines', icon: '💋' },
      { name: 'Hyaluronic Acid', benefit: 'Hydrates and plumps for fuller lips', icon: '💧' },
      { name: 'Vitamin C', benefit: 'Brightens dark or pigmented lips', icon: '✨' },
    ],
    benefits: ['Visibly plumper lips', 'Reduces vertical lip lines', 'Brightens dark lips', 'Non-invasive alternative to fillers', 'Long-term collagen boost'],
    skinTypes: ['All'],
    concerns: ['Thin lips', 'Lip lines', 'Dark lips', 'Loss of volume'],
    size: '10ml',
    inStock: true,
    tags: ['lip-serum', 'plumping', 'peptides', 'lips-care'],
    mainCategory: 'lipscare',
  },
  {
    id: 57,
    name: 'Rose & Sugar Lip Scrub',
    brand: 'Plum',
    category: 'Lip Scrub',
    price: 249,
    mrp: 349,
    rating: 4.6,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Gentle rose and sugar lip scrub that exfoliates dead skin for baby-soft lips.',
    description: 'Remove dead, flaky skin from your lips with this delightful rose and brown sugar lip scrub. Fine sugar crystals gently buff away rough patches while rosehip oil and vitamin E deeply nourish, leaving lips irresistibly soft and perfectly prepped for your lip colour. Lickable, natural formula.',
    howToUse: 'Apply a small amount to dry or damp lips. Gently massage in circular motions for 30-60 seconds. Rinse off or wipe away with a soft cloth. Follow with lip balm. Use 2-3 times a week.',
    ingredients: ['Brown Sugar', 'Rosa Canina (Rosehip) Seed Oil', 'Honey', 'Coconut Oil', 'Vitamin E', 'Beeswax', 'Natural Rose Fragrance'],
    keyIngredients: [
      { name: 'Brown Sugar', benefit: 'Gentle physical exfoliation of dead skin', icon: '🍬' },
      { name: 'Rosehip Oil', benefit: 'Nourishes and brightens lip skin', icon: '🌹' },
      { name: 'Honey', benefit: 'Antibacterial and deeply moisturising', icon: '🍯' },
    ],
    benefits: ['Removes flaky lip skin', 'Preps lips for lip colour', 'Natural edible formula', 'Softens and nourishes', 'Beautiful rose scent'],
    skinTypes: ['All'],
    concerns: ['Chapped lips', 'Rough lip skin', 'Flakiness'],
    size: '25g',
    inStock: true,
    tags: ['lip-scrub', 'rose', 'exfoliating', 'lips-care'],
    mainCategory: 'lipscare',
  },
  {
    id: 58,
    name: 'Overnight Honey Lip Mask',
    brand: 'Dot & Key',
    category: 'Lip Mask',
    price: 399,
    mrp: 549,
    rating: 4.8,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1600428863598-3ef3a8c50f90?w=600&h=600&fit=crop&q=80',
    badge: 'Fan Fave',
    badgeBg: '#C2185B',
    shortDesc: 'Intensive overnight honey and shea butter lip mask for deeply repaired, plump lips by morning.',
    description: 'Wake up to perfectly soft, plump lips with this indulgent overnight lip mask. A rich blend of raw Honey, Shea Butter, Hyaluronic Acid, and Vitamin E works while you sleep to deeply repair, moisturise, and restore lip texture. Can also be used as an intensive daytime lip treatment.',
    howToUse: 'Apply a thick layer to clean lips before bed. Leave on overnight. In the morning, gently wipe off any excess with a soft cloth or rinse. For daytime use, apply as needed for moisture.',
    ingredients: ['Mel (Honey)', 'Butyrospermum Parkii (Shea Butter)', 'Sodium Hyaluronate', 'Tocopherol (Vitamin E)', 'Ceramide NP', 'Beeswax', 'Lanolin', 'Natural Honey Fragrance'],
    keyIngredients: [
      { name: 'Raw Honey', benefit: 'Antibacterial, heals and repairs lip skin', icon: '🍯' },
      { name: 'Shea Butter', benefit: 'Intense moisture seal overnight', icon: '🧈' },
      { name: 'Hyaluronic Acid', benefit: 'Plumps and hydrates from within', icon: '💧' },
    ],
    benefits: ['Intensely repaired lips by morning', 'Removes dryness and chapping', 'Plumping overnight effect', 'Safe to ingest accidentally', 'Perfect for severely chapped lips'],
    skinTypes: ['All'],
    concerns: ['Severely chapped lips', 'Dryness', 'Lip repair'],
    size: '15ml',
    inStock: true,
    tags: ['lip-mask', 'overnight', 'honey', 'lips-care', 'intensive'],
    mainCategory: 'lipscare',
  },

  // ── HAIRCARE (IDs 60–64) ─────────────────────────────────────────────────
  {
    id: 60,
    name: 'Keratin Smoothing Hair Serum',
    brand: 'DermIQ',
    category: 'Hair Serum',
    price: 599,
    mrp: 899,
    rating: 4.7,
    reviews: 1876,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=600&fit=crop&q=80',
    badge: 'Bestseller',
    badgeBg: '#5C35D4',
    shortDesc: 'Lightweight keratin and argan oil serum that tames frizz and adds brilliant shine.',
    description: 'Transform dull, frizzy hair with this professional-grade hair serum. Hydrolysed Keratin fills in hair shaft gaps to smooth the cuticle, while Argan Oil adds intense shine and manageability. The lightweight formula won\'t weigh hair down — perfect for all hair types.',
    howToUse: 'Apply 2-3 drops to damp or dry hair. Focus on mid-lengths and ends. Do not apply directly to roots. Style as usual. For extra protection, apply before heat styling.',
    ingredients: ['Hydrolysed Keratin', 'Argania Spinosa (Argan) Oil', 'Cyclomethicone', 'Dimethicone', 'Vitamin E', 'Silk Amino Acids', 'Panthenol'],
    keyIngredients: [
      { name: 'Hydrolysed Keratin', benefit: 'Fills hair shaft gaps, reduces breakage', icon: '💎' },
      { name: 'Argan Oil', benefit: 'Adds brilliant shine and softness', icon: '✨' },
      { name: 'Silk Amino Acids', benefit: 'Smoothens cuticle, reduces frizz', icon: '🦋' },
    ],
    benefits: ['Eliminates frizz instantly', 'Adds mirror-like shine', 'Protects from heat damage', 'Smoothens hair cuticle', 'Works on all hair types'],
    skinTypes: ['All hair types'],
    concerns: ['Frizz', 'Dullness', 'Damage', 'Breakage'],
    size: '50ml',
    inStock: true,
    tags: ['hair-serum', 'keratin', 'frizz', 'haircare', 'argan'],
    mainCategory: 'haircare',
  },
  {
    id: 61,
    name: 'Bhringraj & Neem Scalp Oil',
    brand: 'Kama Ayurveda',
    category: 'Scalp Oil',
    price: 749,
    mrp: 1099,
    rating: 4.6,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=600&fit=crop&q=80',
    badge: 'Ayurvedic',
    badgeBg: '#5C35D4',
    shortDesc: 'Traditional Bhringraj and Neem scalp oil for hair growth, dandruff control, and scalp health.',
    description: 'A time-tested Ayurvedic blend of Bhringraj (Eclipta prostrata), Neem, and Amla in a base of cold-pressed Sesame Oil. Bhringraj is clinically shown to promote hair growth by stimulating follicles, while Neem\'s antibacterial properties combat dandruff and scalp infections. Regular use improves hair density and thickness.',
    howToUse: 'Warm the oil slightly. Apply to scalp using fingertips, massaging in circular motions for 5-10 minutes. Leave for minimum 1 hour, or overnight for best results. Wash with a mild shampoo. Use 2-3 times weekly.',
    ingredients: ['Eclipta Prostrata (Bhringraj) Extract', 'Azadirachta Indica (Neem) Oil', 'Phyllanthus Emblica (Amla) Extract', 'Sesamum Indicum (Sesame) Oil', 'Trigonella Foenum-Graecum (Fenugreek) Extract', 'Coconut Oil'],
    keyIngredients: [
      { name: 'Bhringraj', benefit: 'Stimulates hair follicles for growth', icon: '🌿' },
      { name: 'Neem Oil', benefit: 'Eliminates dandruff and scalp infections', icon: '🍃' },
      { name: 'Amla', benefit: 'Strengthens hair roots and prevents greying', icon: '💚' },
    ],
    benefits: ['Promotes hair growth', 'Eliminates dandruff', 'Strengthens hair roots', 'Reduces premature greying', 'Improves scalp health'],
    skinTypes: ['All scalp types'],
    concerns: ['Hair fall', 'Dandruff', 'Scalp health', 'Hair growth'],
    size: '100ml',
    inStock: true,
    tags: ['scalp-oil', 'bhringraj', 'ayurvedic', 'haircare', 'hair-growth'],
    mainCategory: 'haircare',
  },
  {
    id: 62,
    name: 'Anti-Hairfall Biotin Shampoo',
    brand: 'DermIQ',
    category: 'Shampoo',
    price: 399,
    mrp: 599,
    rating: 4.5,
    reviews: 3102,
    image: 'https://images.unsplash.com/photo-1631390009-90465ff72860?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Sulphate-free Biotin shampoo that reduces hair fall by 80% in 4 weeks.',
    description: 'India\'s most reviewed anti-hairfall shampoo, now sulphate-free. Packed with Biotin, Keratin Amino Acids, and Saw Palmetto extract, this scientifically formulated shampoo strengthens hair from root to tip, significantly reduces shedding, and creates visible volume. Dermatologically tested.',
    howToUse: 'Wet hair thoroughly. Apply a coin-sized amount, lather well, and massage into scalp for 2 minutes. Rinse thoroughly. For best results, follow with Anti-Hairfall Conditioner. Use 3-4 times weekly.',
    ingredients: ['Biotin (Vitamin B7)', 'Hydrolysed Keratin', 'Serenoa Repens (Saw Palmetto) Extract', 'Niacinamide', 'Panthenol', 'Sodium Cocoyl Isethionate', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Biotin', benefit: 'Strengthens hair structure from within', icon: '💊' },
      { name: 'Saw Palmetto', benefit: 'Blocks DHT, reduces hair fall', icon: '🌿' },
      { name: 'Keratin Amino Acids', benefit: 'Repairs damaged hair shaft', icon: '🧬' },
    ],
    benefits: ['Reduces hair fall by 80%', 'Sulphate and paraben-free', 'Adds visible volume', 'Strengthens from root to tip', 'Dermatologically tested'],
    skinTypes: ['All hair types', 'Thinning hair'],
    concerns: ['Hair fall', 'Thinning hair', 'Breakage'],
    size: '200ml',
    inStock: true,
    tags: ['shampoo', 'anti-hairfall', 'biotin', 'haircare', 'sulphate-free'],
    mainCategory: 'haircare',
  },
  {
    id: 63,
    name: 'Protein Repair Hair Mask',
    brand: 'Dot & Key',
    category: 'Hair Mask',
    price: 499,
    mrp: 749,
    rating: 4.8,
    reviews: 1456,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    badge: 'Deep Repair',
    badgeBg: '#5C35D4',
    shortDesc: '3-minute protein hair mask for intense repair of damaged, bleached, and chemically treated hair.',
    description: 'Rescue severely damaged hair in just 3 minutes with this intensive protein treatment. Hydrolysed Wheat Protein and Keratin penetrate the hair shaft to repair breakage from bleaching, heat, and chemical treatments. The rich, creamy formula also contains Argan Oil and Avocado Butter for deep conditioning.',
    howToUse: 'Shampoo hair and gently squeeze out excess water. Apply mask generously from mid-lengths to ends. Leave for 3-5 minutes. Rinse thoroughly with cool water. Use once a week or as needed.',
    ingredients: ['Hydrolysed Wheat Protein', 'Hydrolysed Keratin', 'Argania Spinosa (Argan) Oil', 'Persea Gratissima (Avocado) Butter', 'Panthenol', 'Cetyl Alcohol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Hydrolysed Wheat Protein', benefit: 'Rebuilds damaged hair from within', icon: '🌾' },
      { name: 'Argan Oil', benefit: 'Intense shine and smoothness', icon: '✨' },
      { name: 'Avocado Butter', benefit: 'Rich conditioning and nourishment', icon: '🥑' },
    ],
    benefits: ['Repairs bleached and damaged hair', 'Works in just 3 minutes', 'Eliminates breakage', 'Restores shine and softness', 'Salon-quality results at home'],
    skinTypes: ['Damaged', 'Dry', 'Chemically treated hair'],
    concerns: ['Damage', 'Breakage', 'Dryness', 'Split ends'],
    size: '200g',
    inStock: true,
    tags: ['hair-mask', 'protein', 'repair', 'haircare', 'damaged'],
    mainCategory: 'haircare',
  },
  {
    id: 64,
    name: 'Waterless Dry Shampoo Spray',
    brand: 'Pilgrim',
    category: 'Dry Shampoo',
    price: 449,
    mrp: 649,
    rating: 4.4,
    reviews: 876,
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Invisible dry shampoo that absorbs oil and refreshes hair between washes in 60 seconds.',
    description: 'Refresh greasy, flat hair in under 60 seconds without water. This invisible aerosol dry shampoo uses fine Tapioca Starch and Rice Flour to absorb excess oil, add volume, and leave hair looking and feeling freshly washed. Completely invisible on all hair colours — no white residue.',
    howToUse: 'Shake can well. Hold 20-30cm from hair. Spray onto oily roots in sections. Wait 30 seconds. Massage in with fingertips. Brush through. Style as desired.',
    ingredients: ['Isobutane (Propellant)', 'Alcohol Denat.', 'Tapioca Starch', 'Oryza Sativa (Rice) Flour', 'Silica', 'Parfum', 'Tocopheryl Acetate'],
    keyIngredients: [
      { name: 'Tapioca Starch', benefit: 'Absorbs scalp oil without white residue', icon: '🌿' },
      { name: 'Rice Flour', benefit: 'Adds instant volume and texture', icon: '🌾' },
      { name: 'Silica', benefit: 'Mattifies and extends freshness', icon: '✨' },
    ],
    benefits: ['Absorbs oil in 60 seconds', 'Invisible on all hair colours', 'Adds volume and texture', 'Extends time between washes', 'Great for travel'],
    skinTypes: ['All hair types'],
    concerns: ['Oily scalp', 'Flat hair', 'Convenience'],
    size: '150ml',
    inStock: true,
    tags: ['dry-shampoo', 'haircare', 'travel', 'volume'],
    mainCategory: 'haircare',
  },

  // ── SUPPLEMENTS (IDs 70–74) ──────────────────────────────────────────────
  {
    id: 70,
    name: 'Marine Collagen Peptides Powder',
    brand: 'DermIQ',
    category: 'Collagen',
    price: 1499,
    mrp: 2199,
    rating: 4.8,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop&q=80',
    badge: 'Clinical Grade',
    badgeBg: '#D4A853',
    shortDesc: 'Type I & III marine collagen peptides with Vitamin C for skin elasticity and anti-aging.',
    description: 'Our premium Marine Collagen Peptides are derived from sustainably sourced deep-sea fish and hydrolysed to low molecular weight for maximum bioavailability. Type I and III collagen combined with Vitamin C (essential for collagen synthesis) and Hyaluronic Acid supports skin elasticity, reduces fine lines, and improves nail and joint health.',
    howToUse: 'Mix one scoop (10g) with water, juice, or smoothie daily. Unflavoured and odourless. For best results, take consistently for minimum 8 weeks. Store in a cool, dry place.',
    ingredients: ['Hydrolysed Marine Collagen Peptides (Type I & III)', 'Ascorbic Acid (Vitamin C)', 'Sodium Hyaluronate', 'Biotin', 'Zinc'],
    keyIngredients: [
      { name: 'Marine Collagen (Type I & III)', benefit: 'Boosts skin elasticity, reduces fine lines', icon: '🐟' },
      { name: 'Vitamin C', benefit: 'Enables collagen synthesis in the body', icon: '🍊' },
      { name: 'Hyaluronic Acid', benefit: 'Internally hydrates skin for plumpness', icon: '💧' },
    ],
    benefits: ['Reduces fine lines and wrinkles', 'Improves skin elasticity', 'Strengthens nails and hair', 'Supports joint health', 'High bioavailability marine source'],
    skinTypes: ['All'],
    concerns: ['Anti-aging', 'Skin elasticity', 'Fine lines', 'Nail health'],
    size: '300g (30 servings)',
    inStock: true,
    tags: ['collagen', 'supplements', 'anti-aging', 'marine-collagen'],
    mainCategory: 'supplements',
  },
  {
    id: 71,
    name: 'Biotin 10000mcg + Zinc Complex',
    brand: 'DermIQ',
    category: 'Hair & Nail Supplement',
    price: 849,
    mrp: 1299,
    rating: 4.7,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=600&h=600&fit=crop&q=80',
    badge: 'Top Seller',
    badgeBg: '#D4A853',
    shortDesc: 'High-dose Biotin with Zinc and Selenium for strong hair, nails, and glowing skin.',
    description: 'Clinical-dose Biotin (10,000mcg) combined with Zinc, Selenium, and Vitamin B complex provides comprehensive support for hair growth, nail strength, and skin health. Biotin plays a crucial role in keratin production while Zinc supports sebum regulation and wound healing. Clinically trialled — visible results in 90 days.',
    howToUse: 'Take 1 tablet daily with a meal. For hair growth benefits, use consistently for minimum 3 months. Keep out of reach of children. Consult a doctor if pregnant or on medication.',
    ingredients: ['Biotin 10,000mcg', 'Zinc 15mg', 'Selenium 55mcg', 'Vitamin B12 1000mcg', 'Folic Acid 400mcg', 'Vitamin D3 1000IU'],
    keyIngredients: [
      { name: 'Biotin 10,000mcg', benefit: 'High-dose support for hair and nail keratin', icon: '💊' },
      { name: 'Zinc 15mg', benefit: 'Regulates sebum, supports skin healing', icon: '⚡' },
      { name: 'Selenium', benefit: 'Antioxidant protection for scalp health', icon: '🛡️' },
    ],
    benefits: ['Reduces hair fall significantly', 'Strengthens brittle nails', 'Improves skin clarity', 'Results in 90 days', 'Clinically trialled formulation'],
    skinTypes: ['All'],
    concerns: ['Hair fall', 'Weak nails', 'Skin health'],
    size: '60 tablets',
    inStock: true,
    tags: ['biotin', 'supplements', 'hair-growth', 'nails', 'zinc'],
    mainCategory: 'supplements',
  },
  {
    id: 72,
    name: 'Skin Radiance Glow Vitamins',
    brand: 'Wellbeing Nutrition',
    category: 'Skin Supplement',
    price: 999,
    mrp: 1499,
    rating: 4.6,
    reviews: 876,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&h=600&fit=crop&q=80',
    badge: 'Glow Formula',
    badgeBg: '#D4A853',
    shortDesc: 'Antioxidant-rich glow vitamins with Astaxanthin, Glutathione, and Vitamin C for lit-from-within glow.',
    description: 'Achieve that lit-from-within glow with this clinically formulated skin supplement. Astaxanthin (the world\'s most powerful antioxidant), Glutathione, and stabilised Vitamin C work synergistically to protect skin from oxidative stress, fade pigmentation from within, and deliver a visible glow. Also supports immune health.',
    howToUse: 'Take 2 capsules daily with meals. Morning intake recommended for best antioxidant benefits throughout the day. Use consistently for minimum 60 days.',
    ingredients: ['Astaxanthin 4mg', 'Glutathione 250mg', 'Ascorbic Acid (Vitamin C) 500mg', 'Mixed Tocopherols (Vitamin E)', 'Coenzyme Q10 50mg', 'Resveratrol 100mg'],
    keyIngredients: [
      { name: 'Astaxanthin 4mg', benefit: 'World\'s strongest antioxidant for skin glow', icon: '🌟' },
      { name: 'Glutathione 250mg', benefit: 'Systemic brightening and pigmentation reduction', icon: '✨' },
      { name: 'Coenzyme Q10', benefit: 'Cellular energy for skin repair', icon: '⚡' },
    ],
    benefits: ['Visible glow in 60 days', 'Fades pigmentation from within', 'Protects from oxidative damage', 'Boosts immune health', 'Anti-aging at cellular level'],
    skinTypes: ['All'],
    concerns: ['Dull skin', 'Pigmentation', 'Anti-aging', 'Glow'],
    size: '60 capsules',
    inStock: true,
    tags: ['skin-vitamins', 'supplements', 'glow', 'antioxidant', 'glutathione'],
    mainCategory: 'supplements',
  },
  {
    id: 73,
    name: 'Omega-3 Fish Oil 1000mg',
    brand: 'DermIQ',
    category: 'Omega-3',
    price: 699,
    mrp: 999,
    rating: 4.5,
    reviews: 1456,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=600&fit=crop&q=80',
    shortDesc: 'High-potency Omega-3 with EPA & DHA for skin barrier, inflammation control, and brain health.',
    description: 'Premium quality Omega-3 Fish Oil from sustainably sourced cold-water fish. Each capsule delivers 300mg EPA and 200mg DHA — the most bioactive forms of Omega-3 that directly support skin barrier function, reduce inflammation (including acne and eczema), and support cardiovascular and brain health.',
    howToUse: 'Take 2-3 softgels daily with meals. Refrigerate after opening to maintain freshness. Individuals on blood thinners should consult a doctor before use.',
    ingredients: ['Fish Oil Concentrate 1000mg (EPA 300mg, DHA 200mg)', 'Tocopheryl Acetate (Vitamin E)', 'Gelatin Capsule Shell'],
    keyIngredients: [
      { name: 'EPA 300mg', benefit: 'Reduces inflammation, calms acne and eczema', icon: '🐟' },
      { name: 'DHA 200mg', benefit: 'Supports skin barrier and brain health', icon: '🧠' },
      { name: 'Vitamin E', benefit: 'Prevents fish oil oxidation, skin antioxidant', icon: '💛' },
    ],
    benefits: ['Reduces acne inflammation', 'Improves skin hydration', 'Supports heart health', 'Brain and mood support', 'High bioavailability EPA/DHA'],
    skinTypes: ['All'],
    concerns: ['Acne', 'Inflammation', 'Dry skin', 'Eczema'],
    size: '60 softgels',
    inStock: true,
    tags: ['omega-3', 'supplements', 'fish-oil', 'inflammation', 'skin-health'],
    mainCategory: 'supplements',
  },
  {
    id: 74,
    name: 'Gut & Skin Probiotic Complex',
    brand: 'Wellbeing Nutrition',
    category: 'Probiotic',
    price: 1199,
    mrp: 1799,
    rating: 4.7,
    reviews: 654,
    image: 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=600&h=600&fit=crop&q=80',
    badge: 'Gut-Skin Axis',
    badgeBg: '#D4A853',
    shortDesc: '10 billion CFU probiotic for improved gut health, reduced acne, and glowing skin.',
    description: 'The gut-skin connection is real. This advanced probiotic supplement contains 10 strains of beneficial bacteria at 10 billion CFU, specifically selected to support the gut-skin axis. Clinical studies show that improving gut microbiome diversity can significantly reduce acne, eczema flares, and skin inflammation while improving overall skin clarity.',
    howToUse: 'Take 1 capsule daily on an empty stomach or with a meal. Refrigerate for best results. Take consistently for minimum 60 days. Safe to take alongside other supplements.',
    ingredients: ['Lactobacillus acidophilus', 'Bifidobacterium longum', 'Lactobacillus rhamnosus', 'Lactobacillus plantarum', 'Inulin (Prebiotic Fibre)', '7 additional probiotic strains (10B CFU total)'],
    keyIngredients: [
      { name: '10B CFU Probiotics', benefit: 'Restores gut microbiome for skin health', icon: '🦠' },
      { name: 'Lactobacillus rhamnosus', benefit: 'Clinically reduces eczema and acne', icon: '🌿' },
      { name: 'Inulin Prebiotic', benefit: 'Feeds beneficial bacteria for sustained effect', icon: '🌱' },
    ],
    benefits: ['Reduces acne from the inside', 'Improves gut health and digestion', 'Reduces eczema flares', 'Improves skin clarity', '10 probiotic strains for diversity'],
    skinTypes: ['All'],
    concerns: ['Acne', 'Eczema', 'Gut health', 'Skin clarity'],
    size: '30 capsules',
    inStock: true,
    tags: ['probiotics', 'supplements', 'gut-health', 'acne', 'skin-health'],
    mainCategory: 'supplements',
  },

  // ── BABY CARE (IDs 80–83) ────────────────────────────────────────────────
  {
    id: 80,
    name: 'Gentle Baby Moisturising Lotion',
    brand: 'Mama Earth',
    category: 'Baby Moisturiser',
    price: 299,
    mrp: 449,
    rating: 4.9,
    reviews: 3456,
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=600&h=600&fit=crop&q=80',
    badge: 'Paed. Tested',
    badgeBg: '#4ECDC4',
    shortDesc: 'Paediatrician-tested baby lotion with oat and chamomile for soft, healthy baby skin.',
    description: 'Specially formulated for delicate newborn and baby skin, this paediatrician-tested moisturising lotion is free from all harmful chemicals including parabens, sulphates, mineral oil, and artificial fragrance. Gentle Colloidal Oat and Chamomile soothe and moisturise sensitive baby skin. Tear-free and pH-balanced for babies.',
    howToUse: 'Apply gently to baby\'s clean skin after bath. Massage softly with warm hands. Safe for daily use on face and body. Avoid contact with eyes.',
    ingredients: ['Colloidal Oatmeal', 'Chamomilla Recutita (Chamomile) Extract', 'Glycerin', 'Allantoin', 'Ceramide NP', 'Sweet Almond Oil', 'Panthenol', 'Aqua'],
    keyIngredients: [
      { name: 'Colloidal Oat', benefit: 'Soothes and protects delicate baby skin', icon: '🌾' },
      { name: 'Chamomile Extract', benefit: 'Calms irritation and redness', icon: '🌼' },
      { name: 'Ceramides', benefit: 'Maintains baby\'s natural skin barrier', icon: '🛡️' },
    ],
    benefits: ['Safe for newborns', 'Paediatrician tested', 'Free from 25 harmful chemicals', 'Soothes dry and irritated skin', 'Daily use gentle formula'],
    skinTypes: ['Baby skin', 'Sensitive'],
    concerns: ['Baby dryness', 'Skin sensitivity', 'Nappy rash prevention'],
    size: '200ml',
    inStock: true,
    tags: ['baby-moisturiser', 'babycare', 'gentle', 'oat', 'paediatrician'],
    mainCategory: 'babycare',
  },
  {
    id: 81,
    name: 'Tear-Free Gentle Baby Wash',
    brand: 'DermIQ',
    category: 'Baby Wash',
    price: 349,
    mrp: 499,
    rating: 4.8,
    reviews: 2187,
    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Ultra-gentle 2-in-1 tear-free baby wash and shampoo with coconut and calendula.',
    description: 'This 2-in-1 baby wash and shampoo is as gentle as water. Formulated with mild surfactants derived from coconut oil and enriched with Calendula extract and Panthenol, it effectively cleanses baby\'s skin and hair without causing tears or dryness. Dermatologically tested. Suitable from birth.',
    howToUse: 'Apply a small amount to wet skin or hair. Lather gently. Rinse thoroughly. For newborns, dilute with water for extra gentleness.',
    ingredients: ['Sodium Cocoyl Isethionate', 'Calendula Officinalis Flower Extract', 'Panthenol', 'Glycerin', 'Allantoin', 'Sodium Chloride', 'Citric Acid', 'Aqua'],
    keyIngredients: [
      { name: 'Coconut-derived Surfactants', benefit: 'Gentle cleansing without irritation', icon: '🥥' },
      { name: 'Calendula Extract', benefit: 'Soothes and protects sensitive skin', icon: '🌼' },
      { name: 'Panthenol', benefit: 'Conditions both skin and baby hair', icon: '💧' },
    ],
    benefits: ['Tear-free formula', '2-in-1 body and hair wash', 'Suitable from birth', 'Dermatologically tested', 'No harmful chemicals'],
    skinTypes: ['Baby skin'],
    concerns: ['Baby cleansing', 'Gentle care'],
    size: '250ml',
    inStock: true,
    tags: ['baby-wash', 'babycare', 'tear-free', 'gentle', 'calendula'],
    mainCategory: 'babycare',
  },
  {
    id: 82,
    name: 'Zinc Oxide Diaper Rash Cream',
    brand: 'Mama Earth',
    category: 'Diaper Cream',
    price: 249,
    mrp: 349,
    rating: 4.9,
    reviews: 4521,
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=600&h=600&fit=crop&q=80',
    badge: 'Must Have',
    badgeBg: '#4ECDC4',
    shortDesc: '40% Zinc Oxide diaper rash cream that heals and prevents nappy rash in 24 hours.',
    description: 'Trusted by over 4 lakh parents, this thick Zinc Oxide barrier cream treats and prevents diaper rash effectively. The high concentration of Zinc Oxide (40%) creates a protective barrier against wetness and irritants, while Calendula and Chamomile soothe already irritated skin. Works within 24 hours.',
    howToUse: 'Clean and dry baby\'s diaper area thoroughly. Apply a thick layer of cream at every diaper change or as needed. No need to remove all cream at each change — add a fresh layer.',
    ingredients: ['Zinc Oxide 40%', 'Calendula Officinalis Extract', 'Chamomilla Recutita (Chamomile) Extract', 'White Petrolatum', 'Dimethicone', 'Lanolin', 'Sweet Almond Oil'],
    keyIngredients: [
      { name: 'Zinc Oxide 40%', benefit: 'Creates moisture barrier, heals rash fast', icon: '🛡️' },
      { name: 'Calendula', benefit: 'Soothes and repairs irritated skin', icon: '🌼' },
      { name: 'Chamomile', benefit: 'Anti-inflammatory, calms redness', icon: '🌸' },
    ],
    benefits: ['Heals diaper rash in 24 hours', 'Prevents rash recurrence', 'Creates effective moisture barrier', 'Soothes sore skin', 'Safe for newborns'],
    skinTypes: ['Baby skin'],
    concerns: ['Diaper rash', 'Nappy irritation'],
    size: '100g',
    inStock: true,
    tags: ['diaper-rash', 'zinc-oxide', 'babycare', 'nappy-cream'],
    mainCategory: 'babycare',
  },
  {
    id: 83,
    name: 'Baby Mineral Sunscreen SPF 30',
    brand: 'DermIQ',
    category: 'Baby Sunscreen',
    price: 449,
    mrp: 649,
    rating: 4.7,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&q=80',
    badge: 'Mineral Only',
    badgeBg: '#4ECDC4',
    shortDesc: 'Mineral-only SPF 30 baby sunscreen with zero chemical filters. Safe from 6 months.',
    description: 'Specially developed for baby and toddler skin (6 months+), this mineral-only sunscreen uses non-nano Zinc Oxide for safe, effective sun protection. Free from all chemical UV filters, fragrances, and common irritants. Water-resistant formula is perfect for beach and pool days.',
    howToUse: 'Apply 15-20 minutes before sun exposure. Apply liberally to all exposed skin. Reapply after water activity or every 2 hours. Avoid direct eye contact. For babies under 6 months, keep out of direct sunlight.',
    ingredients: ['Zinc Oxide 15% (Non-Nano)', 'Titanium Dioxide 3%', 'Calendula Extract', 'Chamomile Extract', 'Glycerin', 'Caprylic/Capric Triglyceride', 'Beeswax', 'Aqua'],
    keyIngredients: [
      { name: 'Non-Nano Zinc Oxide', benefit: 'Safe mineral protection for baby skin', icon: '☀️' },
      { name: 'Calendula', benefit: 'Soothes while protecting from sun', icon: '🌼' },
      { name: 'Titanium Dioxide', benefit: 'Additional mineral UV barrier', icon: '🛡️' },
    ],
    benefits: ['Safe for babies 6 months+', 'No chemical UV filters', 'Water-resistant formula', 'Soothing natural extracts', 'Dermatologically tested'],
    skinTypes: ['Baby skin', 'Sensitive'],
    concerns: ['Sun protection', 'Baby skin safety'],
    size: '60g',
    inStock: true,
    tags: ['baby-sunscreen', 'babycare', 'mineral', 'spf30', 'safe'],
    mainCategory: 'babycare',
  },

  // ── COLOR COSMETICS (IDs 90–94) ──────────────────────────────────────────
  {
    id: 90,
    name: 'Tinted SPF 40 Moisturiser',
    brand: 'DermIQ',
    category: 'Tinted Moisturiser',
    price: 899,
    mrp: 1299,
    rating: 4.8,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&h=600&fit=crop&q=80',
    badge: 'Skin Tint',
    badgeBg: '#FF6B6B',
    shortDesc: '5-in-1 tinted moisturiser with SPF 40, skincare actives, and light buildable coverage.',
    description: 'Skip multiple steps with this 5-in-1 tinted moisturiser that combines SPF 40 protection, hydrating skincare actives (Niacinamide, Hyaluronic Acid), and light-to-medium buildable coverage. Available in 6 inclusive shades matching Indian skin tones. Gives a natural, dewy finish that looks like your skin but better.',
    howToUse: 'Apply as the last step of your skincare routine. Blend with fingers or a damp sponge. Use alone for natural coverage or under foundation for extra hold. Top with SPF spray for outdoor reapplication.',
    ingredients: ['Zinc Oxide 12%', 'Niacinamide 3%', 'Sodium Hyaluronate', 'Iron Oxides (CI 77491, CI 77492, CI 77499)', 'Glycerin', 'Dimethicone', 'Vitamin E', 'Aqua'],
    keyIngredients: [
      { name: 'SPF 40 Zinc Oxide', benefit: 'Broad-spectrum UV protection with coverage', icon: '☀️' },
      { name: 'Niacinamide 3%', benefit: 'Controls oil, minimises pores under tint', icon: '🔬' },
      { name: 'Hyaluronic Acid', benefit: 'Hydrates skin for dewy finish', icon: '💧' },
    ],
    benefits: ['SPF 40 + light coverage in one', '6 inclusive Indian skin shades', 'Dewy natural finish', 'Skincare ingredients inside', 'Buildable coverage'],
    skinTypes: ['All skin types'],
    concerns: ['Sun protection', 'Natural coverage', 'Glow'],
    size: '30ml',
    inStock: true,
    tags: ['tinted-moisturiser', 'spf', 'color-cosmetics', 'skin-tint', 'natural'],
    mainCategory: 'colorcosmetics',
  },
  {
    id: 91,
    name: 'Serum Lip Tint — 6 Shades',
    brand: 'DermIQ',
    category: 'Lip Colour',
    price: 449,
    mrp: 649,
    rating: 4.7,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1586495777744-4e6b0c8b9e0f?w=600&h=600&fit=crop&q=80',
    badge: 'Caring Colour',
    badgeBg: '#FF6B6B',
    shortDesc: 'Comfortable, caring lip tint with Hyaluronic Acid that gives sheer-to-buildable colour.',
    description: 'This lip tint crosses the boundary between skincare and makeup. Formulated with Hyaluronic Acid, Vitamin E, and Squalane, it gives lips a sheer-to-buildable colour wash while actively caring for lips. Available in 6 wearable shades from nude-pink to deep berry. Non-drying, comfortable, and beautiful.',
    howToUse: 'Apply directly to lips. For sheer wash, one layer. For deeper colour, apply 2-3 thin layers. Can be blended with fingertip for an ombre lip look. Remove with micellar water or cleansing balm.',
    ingredients: ['Sodium Hyaluronate', 'Tocopherol (Vitamin E)', 'Squalane', 'Hydrogenated Castor Oil', 'Iron Oxides', 'Carnauba Wax', 'Caprylic/Capric Triglyceride'],
    keyIngredients: [
      { name: 'Hyaluronic Acid', benefit: 'Hydrates lips while providing colour', icon: '💧' },
      { name: 'Vitamin E', benefit: 'Nourishes and protects lip skin', icon: '💛' },
      { name: 'Squalane', benefit: 'Comfortable, non-drying wear', icon: '✨' },
    ],
    benefits: ['Colour + care in one', 'Available in 6 shades', 'Non-drying comfortable wear', 'Buildable coverage', 'Suitable for daily use'],
    skinTypes: ['All'],
    concerns: ['Lip colour', 'Lip care', 'Natural look'],
    size: '3.5ml',
    inStock: true,
    tags: ['lip-tint', 'color-cosmetics', 'lip-colour', 'caring', 'hyaluronic'],
    mainCategory: 'colorcosmetics',
  },
  {
    id: 92,
    name: 'Skin-Match BB Cream SPF 20',
    brand: 'Plum',
    category: 'BB Cream',
    price: 699,
    mrp: 999,
    rating: 4.6,
    reviews: 1765,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Lightweight BB cream with SPF 20 that adapts to your skin tone for natural coverage.',
    description: 'This intelligent BB cream uses skin-tone adapting technology to blend seamlessly with all Indian complexions. SPF 20 protection, skin-evening coverage, and active ingredients including Niacinamide and Green Tea antioxidants make this the ultimate multitasker for a no-makeup makeup look.',
    howToUse: 'Apply 2-3 dots to face and blend with fingertips or a sponge in outward strokes. Build coverage as desired. Follow with SPF spray for adequate sun protection outdoors.',
    ingredients: ['Zinc Oxide 5% (SPF 20)', 'Niacinamide 2%', 'Camellia Sinensis (Green Tea) Extract', 'Glycerin', 'Iron Oxides', 'Silica', 'Dimethicone', 'Aqua'],
    keyIngredients: [
      { name: 'Tone-Adapting Pigments', benefit: 'Blends with all Indian skin tones', icon: '🎨' },
      { name: 'Niacinamide 2%', benefit: 'Controls shine under makeup', icon: '🔬' },
      { name: 'Green Tea Extract', benefit: 'Antioxidant protection throughout the day', icon: '🍵' },
    ],
    benefits: ['Adapts to skin tone', 'SPF 20 built-in', 'Natural coverage', 'Controls oil and shine', 'Antioxidant-infused'],
    skinTypes: ['All skin types'],
    concerns: ['Natural coverage', 'Sun protection', 'Oiliness'],
    size: '30ml',
    inStock: true,
    tags: ['bb-cream', 'color-cosmetics', 'spf', 'natural-coverage'],
    mainCategory: 'colorcosmetics',
  },
  {
    id: 93,
    name: 'Full Cover Skin Concealer',
    brand: 'DermIQ',
    category: 'Concealer',
    price: 549,
    mrp: 799,
    rating: 4.7,
    reviews: 876,
    image: 'https://images.unsplash.com/photo-1599733594230-6b823276abcc?w=600&h=600&fit=crop&q=80',
    badge: '12 Shades',
    badgeBg: '#FF6B6B',
    shortDesc: 'High-coverage, non-creasing concealer with Vitamin C for dark circles and blemishes.',
    description: 'This full-coverage, long-lasting concealer covers dark circles, blemishes, and redness without creasing or settling into fine lines. Available in 12 shades for all Indian skin tones from fair to deep. Enriched with Vitamin C to brighten under-eye area over time.',
    howToUse: 'Apply small dots under eyes or on blemishes. Blend with ring finger or damp sponge. Set with a light dusting of setting powder for all-day wear. Layer for maximum coverage.',
    ingredients: ['Ascorbic Acid (Vitamin C) 1%', 'Sodium Hyaluronate', 'Iron Oxides', 'Mica', 'Silica', 'Dimethicone', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Vitamin C 1%', benefit: 'Brightens dark circles over time', icon: '🍊' },
      { name: 'Hyaluronic Acid', benefit: 'Prevents creasing and dryness', icon: '💧' },
      { name: 'Silica', benefit: 'Blurring effect for smooth finish', icon: '✨' },
    ],
    benefits: ['Full coverage dark circles', 'Non-creasing formula', '12 inclusive shades', 'Vitamin C skin benefits', 'Long-lasting wear'],
    skinTypes: ['All skin types'],
    concerns: ['Dark circles', 'Blemishes', 'Redness', 'Coverage'],
    size: '6ml',
    inStock: true,
    tags: ['concealer', 'color-cosmetics', 'dark-circles', 'coverage'],
    mainCategory: 'colorcosmetics',
  },
  {
    id: 94,
    name: 'Baked Glow Blush — 3 Shades',
    brand: 'Pilgrim',
    category: 'Blush',
    price: 599,
    mrp: 899,
    rating: 4.5,
    reviews: 654,
    image: 'https://images.unsplash.com/photo-1599733594230-6b823276abcc?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Buildable baked blush with a natural flush and subtle glow. Available in 3 flattering shades.',
    description: 'These baked powder blushes deliver a natural-looking flush with a soft glow finish. The baked formula blends effortlessly and builds beautifully without looking chalky or patchy. Available in Peachy Nude, Rose Pink, and Coral Flush — shades designed to complement Indian and South Asian skin tones.',
    howToUse: 'Smile and apply to apples of cheeks with a fluffy brush in circular motions. Blend upward toward temples. Layer for more intense colour. Can also be used as a light eyeshadow.',
    ingredients: ['Mica', 'Talc', 'Iron Oxides', 'Titanium Dioxide', 'Dimethicone', 'Silica', 'Magnesium Stearate', 'Tocopheryl Acetate'],
    keyIngredients: [
      { name: 'Baked Mica', benefit: 'Gives natural glow without glitter', icon: '✨' },
      { name: 'Vitamin E', benefit: 'Conditions skin under makeup', icon: '💛' },
      { name: 'Silica', benefit: 'Smooth blending, long-lasting wear', icon: '🎨' },
    ],
    benefits: ['Natural flush finish', '3 shades for Indian skin tones', 'Buildable coverage', 'Doubles as eyeshadow', 'Paraben-free formula'],
    skinTypes: ['All skin types'],
    concerns: ['Colour', 'Natural look', 'Glow'],
    size: '8g',
    inStock: true,
    tags: ['blush', 'color-cosmetics', 'glow', 'baked', 'face-colour'],
    mainCategory: 'colorcosmetics',
  },
]

export const getProductById = (id: number) => ALL_PRODUCTS.find(p => p.id === id)
export const getProductsByCategory = (cat: string) => ALL_PRODUCTS.filter(p => p.category === cat)
export const getProductsByBrand = (brand: string) => ALL_PRODUCTS.filter(p => p.brand === brand)
export const getProductsByMainCategory = (mainCat: string) => ALL_PRODUCTS.filter(p => p.mainCategory === mainCat)

export const BESTSELLERS = ALL_PRODUCTS.filter(p => [1, 2, 3, 4, 5, 6].includes(p.id))
export const NEW_LAUNCHES = ALL_PRODUCTS.filter(p => [7, 8, 9, 10, 11, 12].includes(p.id))
export const BUDGET = ALL_PRODUCTS.filter(p => [13, 7, 9, 4, 8, 14].includes(p.id))

export const MAIN_CATEGORIES = [
  { slug: 'skincare', label: 'Skincare', emoji: '✨', color: '#2D5F5A', bg: '#E8F5E9', image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&h=500&fit=crop&q=80' },
  { slug: 'bodycare', label: 'Body Care', emoji: '🧴', color: '#C8976A', bg: '#FFF3E0', image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&h=500&fit=crop&q=80' },
  { slug: 'lipscare', label: 'Lips Care', emoji: '💋', color: '#C2185B', bg: '#FCE4EC', image: 'https://images.unsplash.com/photo-1586495777744-4e6b0c8b9e0f?w=800&h=500&fit=crop&q=80' },
  { slug: 'haircare', label: 'Hair Care', emoji: '💈', color: '#5C35D4', bg: '#EDE7F6', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=500&fit=crop&q=80' },
  { slug: 'supplements', label: 'Supplements', emoji: '💊', color: '#D4A853', bg: '#FFF8E1', image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=500&fit=crop&q=80' },
  { slug: 'babycare', label: 'Baby Care', emoji: '🍼', color: '#4ECDC4', bg: '#E0F7FA', image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=800&h=500&fit=crop&q=80' },
  { slug: 'colorcosmetics', label: 'Color Cosmetics', emoji: '🎨', color: '#FF6B6B', bg: '#FFF3F3', image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&h=500&fit=crop&q=80' },
]
