export interface Product {
  id: number
  name: string
  brand: string
  category: string
  price: number
  mrp: number
  rating: number
  reviews: number
  image: string
  badge?: string
  badgeBg?: string
  shortDesc: string
  description: string
  howToUse: string
  ingredients: string[]
  keyIngredients: { name: string; benefit: string; icon: string }[]
  benefits: string[]
  skinTypes: string[]
  concerns: string[]
  size: string
  inStock: boolean
  tags: string[]
}

export const ALL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Vitamin C 15% Brightening Serum',
    brand: 'DermIQ',
    category: 'Serum',
    price: 799,
    mrp: 1299,
    rating: 4.9,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    badge: 'Bestseller',
    badgeBg: '#1A2E2B',
    shortDesc: 'Clinical-grade Vitamin C with ferulic acid for visible brightening in 2 weeks.',
    description: 'Our most-loved serum powered by 15% stable Vitamin C (Ascorbic Acid) combined with Ferulic Acid and Vitamin E. This potent antioxidant trio protects skin from free radical damage, visibly fades dark spots, and delivers a natural glow. Lightweight, fast-absorbing formula that works on all skin types without irritation.',
    howToUse: 'Apply 3-4 drops to clean, dry face every morning. Gently pat in. Follow with moisturiser and SPF 50+. Avoid eye area. Start with every other day if new to Vitamin C.',
    ingredients: ['Ascorbic Acid 15%', 'Ferulic Acid 0.5%', 'Tocopherol (Vitamin E)', 'Sodium Hyaluronate', 'Niacinamide 3%', 'Panthenol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Vitamin C 15%', benefit: 'Brightens skin, fades dark spots, boosts collagen', icon: '🍊' },
      { name: 'Ferulic Acid', benefit: 'Stabilises Vitamin C, doubles antioxidant protection', icon: '🌾' },
      { name: 'Vitamin E', benefit: 'Nourishes and protects skin barrier', icon: '💛' },
      { name: 'Hyaluronic Acid', benefit: 'Provides hydration and plumping effect', icon: '💧' },
    ],
    benefits: ['Visibly brightens dull skin in 14 days', 'Fades dark spots and hyperpigmentation', 'Boosts natural collagen production', 'Protects against UV and pollution damage', 'Evens out skin tone'],
    skinTypes: ['Oily', 'Combination', 'Normal', 'Dry'],
    concerns: ['Dark spots', 'Dull skin', 'Uneven tone', 'Anti-aging'],
    size: '30ml',
    inStock: true,
    tags: ['brightening', 'vitamin-c', 'antioxidant', 'morning'],
  },
  {
    id: 2,
    name: 'Hyaluronic Acid 2% + B5 Deep Hydra Gel',
    brand: 'DermIQ',
    category: 'Moisturiser',
    price: 649,
    mrp: 999,
    rating: 4.8,
    reviews: 1876,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Multi-molecular hyaluronic acid gel that locks in 72-hour hydration.',
    description: 'A lightweight gel moisturiser containing three molecular weights of Hyaluronic Acid to hydrate skin at every layer. Combined with Vitamin B5 (Panthenol) for barrier repair, this formula delivers intense hydration without any greasy residue. Perfect for oily and combination skin types.',
    howToUse: 'Apply a pea-sized amount to clean face morning and night. Can be used over serums. Suitable as the final step in AM routine before SPF.',
    ingredients: ['Sodium Hyaluronate (Low, Medium, High MW)', 'Panthenol (B5)', 'Sodium PCA', 'Allantoin', 'Centella Asiatica Extract', 'Glycerin', 'Carbomer', 'Aqua'],
    keyIngredients: [
      { name: 'Hyaluronic Acid (3 weights)', benefit: 'Hydrates all skin layers, plumps fine lines', icon: '💧' },
      { name: 'Vitamin B5', benefit: 'Repairs skin barrier, soothes irritation', icon: '🛡️' },
      { name: 'Centella Asiatica', benefit: 'Calms redness and inflammation', icon: '🌿' },
      { name: 'Allantoin', benefit: 'Smoothens and conditions skin texture', icon: '✨' },
    ],
    benefits: ['72-hour lasting hydration', 'Non-greasy lightweight formula', 'Repairs damaged skin barrier', 'Calms redness and sensitivity', 'Plumps fine lines'],
    skinTypes: ['Oily', 'Combination', 'Normal', 'Sensitive'],
    concerns: ['Dehydration', 'Dullness', 'Sensitivity', 'Fine lines'],
    size: '50ml',
    inStock: true,
    tags: ['hydration', 'gel', 'hyaluronic-acid', 'lightweight'],
  },
  {
    id: 3,
    name: 'Mineral Sunscreen SPF 50+ PA++++',
    brand: 'DermIQ',
    category: 'Sunscreen',
    price: 549,
    mrp: 899,
    rating: 4.9,
    reviews: 3102,
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop&q=80',
    badge: 'SPF 50+',
    badgeBg: '#C8976A',
    shortDesc: 'Invisible mineral sunscreen with zero white cast. Dermatologist recommended.',
    description: 'India\'s first truly invisible mineral sunscreen. Formulated with micronized Zinc Oxide and Titanium Dioxide for broad-spectrum UVA/UVB protection. The PA++++ rating means superior protection against skin aging and darkening. Matte finish, no white cast, water-resistant up to 80 minutes.',
    howToUse: 'Apply generously as the last step of your AM skincare routine. Use 1/4 teaspoon for the face alone. Reapply every 2-3 hours when outdoors. Suitable for daily use.',
    ingredients: ['Zinc Oxide 10%', 'Titanium Dioxide 5%', 'Niacinamide 3%', 'Tocopherol', 'Aloe Vera Extract', 'Dimethicone', 'Caprylic/Capric Triglyceride', 'Aqua'],
    keyIngredients: [
      { name: 'Zinc Oxide 10%', benefit: 'Broad-spectrum UVA/UVB protection', icon: '☀️' },
      { name: 'Titanium Dioxide 5%', benefit: 'Reflects harmful UV rays physically', icon: '🛡️' },
      { name: 'Niacinamide 3%', benefit: 'Minimises pores, controls oil', icon: '🔬' },
      { name: 'Aloe Vera', benefit: 'Soothes and hydrates skin', icon: '🌿' },
    ],
    benefits: ['SPF 50+ PA++++ broad-spectrum protection', 'Zero white cast on all skin tones', 'Matte finish controls oil', 'Water-resistant 80 minutes', 'Suitable for sensitive skin'],
    skinTypes: ['All skin types', 'Sensitive', 'Oily', 'Acne-prone'],
    concerns: ['Sun damage', 'Tanning', 'Premature aging', 'Hyperpigmentation'],
    size: '50g',
    inStock: true,
    tags: ['sunscreen', 'spf50', 'mineral', 'matte', 'daily-protection'],
  },
  {
    id: 4,
    name: 'Gentle Amino Acid Foaming Wash',
    brand: 'DermIQ',
    category: 'Cleanser',
    price: 399,
    mrp: 599,
    rating: 4.7,
    reviews: 1543,
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop&q=80',
    shortDesc: 'pH-balanced amino acid cleanser that cleans without stripping skin\'s natural oils.',
    description: 'A gentle yet effective face wash powered by amino acid-based surfactants — the same building blocks as your skin. Maintains your skin\'s natural pH of 5.5, ensuring the microbiome stays healthy. Creates a soft, creamy lather that removes makeup, sunscreen, and impurities without leaving skin tight or dry.',
    howToUse: 'Wet face with lukewarm water. Apply a small amount to palms, lather, and massage gently onto face in circular motions for 60 seconds. Rinse thoroughly. Use morning and night.',
    ingredients: ['Sodium Cocoyl Glutamate', 'Disodium Cocoyl Glutamate', 'Glycerin', 'Panthenol', 'Allantoin', 'Ceramide NP', 'Niacinamide 2%', 'Citric Acid', 'Aqua'],
    keyIngredients: [
      { name: 'Amino Acid Surfactants', benefit: 'Cleans gently without disrupting pH', icon: '🫧' },
      { name: 'Ceramide NP', benefit: 'Maintains and strengthens skin barrier', icon: '🛡️' },
      { name: 'Panthenol', benefit: 'Conditions and soothes skin post-cleanse', icon: '💚' },
      { name: 'Glycerin', benefit: 'Keeps skin hydrated even after washing', icon: '💧' },
    ],
    benefits: ['Maintains skin\'s natural pH 5.5', 'Removes impurities without over-cleansing', 'Leaves skin soft, not tight', 'Suitable for daily double cleanse', 'Safe for sensitive and acne-prone skin'],
    skinTypes: ['All skin types', 'Sensitive', 'Dry', 'Acne-prone'],
    concerns: ['Sensitivity', 'Dryness post-cleanse', 'Barrier damage'],
    size: '150ml',
    inStock: true,
    tags: ['cleanser', 'gentle', 'amino-acid', 'ph-balanced', 'daily'],
  },
  {
    id: 5,
    name: 'Retinol 0.2% Night Renewal Serum',
    brand: 'Minimalist',
    category: 'Serum',
    price: 699,
    mrp: 999,
    rating: 4.6,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1611080541599-8c6dbde6ed28?w=600&h=600&fit=crop&q=80',
    badge: 'Derma Pick',
    badgeBg: '#2D5F5A',
    shortDesc: 'Beginner-friendly retinol formula encapsulated for zero irritation.',
    description: 'Science-backed retinol serum with 0.2% encapsulated retinol for gradual, controlled release throughout the night. Unlike traditional retinol, our microencapsulated formula minimises irritation, redness, and peeling — perfect for retinol beginners. Contains squalane and peptides to support skin while retinol works.',
    howToUse: 'Use only at night. Apply 3-4 drops after cleansing and toning. Start with 2-3 times a week and gradually increase. Always follow with moisturiser. Use SPF 50+ during the day. Avoid mixing with AHA/BHA on the same night.',
    ingredients: ['Encapsulated Retinol 0.2%', 'Squalane', 'Palmitoyl Tripeptide-1', 'Palmitoyl Tetrapeptide-7', 'Sodium Hyaluronate', 'Niacinamide 2%', 'Tocopherol', 'Aqua'],
    keyIngredients: [
      { name: 'Encapsulated Retinol 0.2%', benefit: 'Renews skin cells, reduces wrinkles and dark spots', icon: '🌙' },
      { name: 'Squalane', benefit: 'Locks in moisture, prevents retinol dryness', icon: '💧' },
      { name: 'Peptides', benefit: 'Boosts collagen, firms and tightens skin', icon: '🧬' },
      { name: 'Niacinamide', benefit: 'Reduces redness from retinol use', icon: '🔬' },
    ],
    benefits: ['Reduces fine lines and wrinkles in 8 weeks', 'Fades acne scars and dark spots', 'Improves skin texture and tone', 'Boosts collagen production', 'Minimal irritation with encapsulation technology'],
    skinTypes: ['Normal', 'Combination', 'Oily'],
    concerns: ['Anti-aging', 'Acne scars', 'Uneven texture', 'Fine lines'],
    size: '30ml',
    inStock: true,
    tags: ['retinol', 'anti-aging', 'night-serum', 'minimalist'],
  },
  {
    id: 6,
    name: 'Ceramide + Hyaluronic Barrier Cream',
    brand: 'DermIQ',
    category: 'Moisturiser',
    price: 849,
    mrp: 1299,
    rating: 4.8,
    reviews: 2103,
    image: 'https://images.unsplash.com/photo-1583248369069-9d91f1640fe6?w=600&h=600&fit=crop&q=80',
    shortDesc: 'Ceramide-rich barrier repair cream for dry, sensitive, and compromised skin.',
    description: 'Clinically formulated with 3 essential ceramides (NP, AP, EOP), cholesterol, and fatty acids in the same ratio found in healthy skin. This barrier-restoring moisturiser is fragrance-free, suitable for eczema-prone skin, and rebuilds the protective layer that keeps moisture in and irritants out.',
    howToUse: 'Apply a generous layer to face and neck morning and night. Can be used on body too. For best results, apply immediately after washing while skin is still slightly damp.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Cholesterol', 'Fatty Acids', 'Sodium Hyaluronate', 'Glycerin', 'Dimethicone', 'Tocopherol', 'Aqua'],
    keyIngredients: [
      { name: 'Ceramides NP+AP+EOP', benefit: 'Rebuilds and strengthens skin barrier', icon: '🏺' },
      { name: 'Cholesterol', benefit: 'Restores lipid balance in skin', icon: '⚖️' },
      { name: 'Hyaluronic Acid', benefit: 'Intense 48-hour hydration', icon: '💧' },
      { name: 'Dimethicone', benefit: 'Creates protective skin film', icon: '🛡️' },
    ],
    benefits: ['Repairs damaged skin barrier', 'Relieves dry and flaky skin', 'Suitable for eczema-prone skin', 'Fragrance-free and hypoallergenic', 'Locks in moisture for 48 hours'],
    skinTypes: ['Dry', 'Sensitive', 'Normal', 'Eczema-prone'],
    concerns: ['Dryness', 'Barrier damage', 'Sensitivity', 'Eczema'],
    size: '60ml',
    inStock: true,
    tags: ['ceramide', 'barrier-repair', 'dry-skin', 'sensitive'],
  },
  {
    id: 7,
    name: 'Niacinamide 10% + Zinc 1% Serum',
    brand: 'Minimalist',
    category: 'Serum',
    price: 449,
    mrp: 699,
    rating: 4.7,
    reviews: 4320,
    image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop&q=80',
    badge: 'Top Rated',
    badgeBg: '#2D5F5A',
    shortDesc: 'India\'s #1 niacinamide serum. Minimises pores and controls oiliness in 4 weeks.',
    description: 'The most straightforward pore-minimising serum available. 10% Niacinamide (Vitamin B3) combined with 1% Zinc PCA reduces the appearance of enlarged pores, balances sebum production, and fades blemishes. A cult favourite backed by 4000+ verified reviews.',
    howToUse: 'Apply 3-4 drops to clean skin, morning and night. Can be mixed with moisturiser. Avoid using with pure Vitamin C on the same step — use them at different times of day.',
    ingredients: ['Niacinamide 10%', 'Zinc PCA 1%', 'Sodium Hyaluronate', 'Panthenol', 'Tamarind Seed Extract', 'Pentylene Glycol', 'Aqua'],
    keyIngredients: [
      { name: 'Niacinamide 10%', benefit: 'Minimises pores, fades dark spots, reduces redness', icon: '🔬' },
      { name: 'Zinc PCA 1%', benefit: 'Controls sebum, prevents breakouts', icon: '⚡' },
      { name: 'Tamarind Extract', benefit: 'Natural AHA for gentle exfoliation', icon: '🌿' },
    ],
    benefits: ['Visibly minimises pores in 4 weeks', 'Controls oiliness and shine', 'Fades post-acne marks', 'Reduces redness and blotchiness', 'Brightens overall complexion'],
    skinTypes: ['Oily', 'Combination', 'Acne-prone'],
    concerns: ['Large pores', 'Oiliness', 'Acne marks', 'Dull skin'],
    size: '30ml',
    inStock: true,
    tags: ['niacinamide', 'pores', 'oily-skin', 'minimalist', 'bestseller'],
  },
  {
    id: 8,
    name: 'Watermelon Glow Sleeping Mask',
    brand: 'Dot & Key',
    category: 'Treatment',
    price: 699,
    mrp: 999,
    rating: 4.8,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1600428863598-3ef3a8c50f90?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Overnight mask with real watermelon extract that wakes you up to glowing skin.',
    description: 'Wake up to visibly glowing, hydrated skin with this overnight treatment mask. Packed with real watermelon extract, hyaluronic acid, and vitamin C, this sleeping mask works while you sleep to replenish, hydrate, and brighten. Gel-cream texture absorbs quickly, leaving no sticky residue on pillows.',
    howToUse: 'Apply as the last step of your night skincare routine. Use 2-3 times a week. Apply a generous, even layer over entire face. Leave on overnight. Rinse in the morning with a gentle cleanser.',
    ingredients: ['Citrullus Lanatus (Watermelon) Fruit Extract 15%', 'Sodium Hyaluronate', 'Ascorbic Acid 3%', 'Niacinamide 2%', 'Aloe Vera Gel', 'Centella Asiatica', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Watermelon Extract 15%', benefit: 'Hydrates, soothes, and provides antioxidants', icon: '🍉' },
      { name: 'Vitamin C 3%', benefit: 'Brightens and evens skin tone overnight', icon: '✨' },
      { name: 'Hyaluronic Acid', benefit: 'Deep overnight hydration', icon: '💧' },
      { name: 'Centella Asiatica', benefit: 'Calms and repairs skin while sleeping', icon: '🌿' },
    ],
    benefits: ['Wake up with visibly glowing skin', 'Deep overnight hydration', 'Fades dark spots while you sleep', 'Gel texture doesn\'t transfer to pillows', 'Refreshes dull and tired skin'],
    skinTypes: ['Normal', 'Dry', 'Combination', 'Sensitive'],
    concerns: ['Dullness', 'Dehydration', 'Dark spots', 'Uneven tone'],
    size: '85g',
    inStock: true,
    tags: ['overnight-mask', 'sleeping-mask', 'glow', 'dot-and-key'],
  },
  {
    id: 9,
    name: 'SPF 50 Invisible Matte Sunscreen',
    brand: 'Pilgrim',
    category: 'Sunscreen',
    price: 599,
    mrp: 899,
    rating: 4.6,
    reviews: 2156,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Ultra-light Korean-formula SPF 50 sunscreen with zero white cast and matte finish.',
    description: 'Inspired by Korean skincare technology, this feather-light sunscreen provides SPF 50 PA++++ protection with an invisible, matte finish. Formulated with a hybrid of chemical and mineral filters, it protects against both UVA and UVB rays while keeping skin oil-free for up to 8 hours.',
    howToUse: 'Apply as last step of skincare. Use ¼ tsp for face. Reapply every 2-3 hours outdoors. Can be worn under makeup. Suitable for daily use.',
    ingredients: ['Homosalate 10%', 'Octisalate 5%', 'Zinc Oxide 3%', 'Niacinamide 3%', 'Silica', 'Glycerin', 'Dimethicone', 'Aqua'],
    keyIngredients: [
      { name: 'Hybrid UV Filters', benefit: 'Complete UVA + UVB protection', icon: '☀️' },
      { name: 'Niacinamide 3%', benefit: 'Controls oil and minimises pores', icon: '🔬' },
      { name: 'Silica', benefit: 'Mattifies skin for 8 hours', icon: '✨' },
    ],
    benefits: ['SPF 50 PA++++ protection', 'Matte finish lasts 8 hours', 'Makeup-friendly base', 'No white cast on deeper skin tones', 'Lightweight Korean formula'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    concerns: ['Sun protection', 'Oiliness', 'Tanning'],
    size: '50g',
    inStock: true,
    tags: ['sunscreen', 'spf50', 'matte', 'pilgrim', 'korean'],
  },
  {
    id: 10,
    name: 'Kojic Acid 2% + Alpha Arbutin Serum',
    brand: 'Plum',
    category: 'Serum',
    price: 549,
    mrp: 799,
    rating: 4.5,
    reviews: 1089,
    image: 'https://images.unsplash.com/photo-1631390009-90465ff72860?w=600&h=600&fit=crop&q=80',
    badge: 'New',
    badgeBg: '#D4856A',
    shortDesc: 'Powerful dark spot corrector with Kojic Acid + Alpha Arbutin for visible results in 3 weeks.',
    description: 'Target stubborn dark spots, melasma, and post-inflammatory hyperpigmentation with this dual-action brightening serum. Kojic Acid inhibits melanin production while Alpha Arbutin gently exfoliates discoloured cells. Results visible in as little as 3 weeks with consistent use.',
    howToUse: 'Apply 3-4 drops to targeted areas (dark spots, melasma patches) or entire face. Use at night. Follow with moisturiser. Wear SPF every morning when using this product.',
    ingredients: ['Kojic Acid 2%', 'Alpha Arbutin 1%', 'Niacinamide 5%', 'Sodium Hyaluronate', 'Vitamin C 3%', 'Panthenol', 'Glycerin', 'Aqua'],
    keyIngredients: [
      { name: 'Kojic Acid 2%', benefit: 'Inhibits melanin for visible spot reduction', icon: '✨' },
      { name: 'Alpha Arbutin 1%', benefit: 'Gently removes discoloured skin cells', icon: '🌸' },
      { name: 'Niacinamide 5%', benefit: 'Reduces inflammation and redness', icon: '🔬' },
    ],
    benefits: ['Fades dark spots in 3 weeks', 'Treats melasma and sun spots', 'Reduces post-acne marks', 'Brightens overall complexion', 'Gentle enough for sensitive skin'],
    skinTypes: ['All skin types'],
    concerns: ['Dark spots', 'Melasma', 'Hyperpigmentation', 'Post-acne marks'],
    size: '30ml',
    inStock: true,
    tags: ['dark-spots', 'kojic-acid', 'brightening', 'plum'],
  },
  {
    id: 11,
    name: 'Peptide Complex Eye Cream',
    brand: 'DermIQ',
    category: 'Treatment',
    price: 999,
    mrp: 1499,
    rating: 4.9,
    reviews: 487,
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=600&h=600&fit=crop&q=80',
    badge: 'Premium',
    badgeBg: '#3D7A74',
    shortDesc: 'Clinical-strength peptide eye cream. Reduces dark circles and crow\'s feet in 4 weeks.',
    description: 'Our most advanced eye treatment featuring 5 targeted peptides proven to reduce the appearance of crow\'s feet, puffiness, and dark circles. The caffeine complex constricts blood vessels to reduce under-eye bags, while ceramides prevent moisture loss around the delicate eye area.',
    howToUse: 'Use morning and night. Apply a small amount (rice grain size) with ring finger to orbital bone area. Pat gently, do not rub. Use consistently for 4+ weeks for best results.',
    ingredients: ['Argireline (Acetyl Hexapeptide-3) 5%', 'Leuphasyl 3%', 'Caffeine 2%', 'Ceramide NP', 'Sodium Hyaluronate', 'Palmitoyl Tripeptide-1', 'Niacinamide', 'Shea Butter', 'Aqua'],
    keyIngredients: [
      { name: 'Argireline 5%', benefit: 'Relaxes expression lines, reduces crow\'s feet', icon: '👁️' },
      { name: 'Caffeine 2%', benefit: 'Reduces puffiness and dark circles', icon: '☕' },
      { name: 'Ceramides', benefit: 'Strengthens delicate eye area barrier', icon: '🛡️' },
      { name: 'Peptide Complex', benefit: 'Firms and tightens under-eye skin', icon: '🧬' },
    ],
    benefits: ['Reduces crow\'s feet in 4 weeks', 'Minimises dark circles and puffiness', 'Hydrates delicate eye area', 'Firms under-eye skin', 'Safe for contact lens wearers'],
    skinTypes: ['All skin types'],
    concerns: ['Dark circles', 'Puffiness', 'Crow\'s feet', 'Eye area aging'],
    size: '15ml',
    inStock: true,
    tags: ['eye-cream', 'peptides', 'dark-circles', 'anti-aging', 'premium'],
  },
  {
    id: 12,
    name: 'AHA 25% + BHA 2% Peeling Solution',
    brand: 'Minimalist',
    category: 'Treatment',
    price: 549,
    mrp: 799,
    rating: 4.7,
    reviews: 3654,
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&h=600&fit=crop&q=80',
    badge: 'Trending',
    badgeBg: '#C8976A',
    shortDesc: '10-minute at-home peel for smooth, glowing skin. Clinically tested formulation.',
    description: 'A powerful chemical exfoliating solution combining 25% AHA (Glycolic, Lactic, Tartaric acids) and 2% BHA (Salicylic Acid) for a complete surface and pore-deep exfoliation. Works in just 10 minutes to dissolve dead skin, unclog pores, and reveal brighter, smoother skin underneath.',
    howToUse: 'PATCH TEST FIRST. Use once weekly. Apply to dry face, avoiding eye and lip area. Leave on for maximum 10 minutes. Rinse thoroughly. Do not use on irritated skin. Always use SPF the next day. Not suitable for beginners.',
    ingredients: ['Glycolic Acid 10%', 'Lactic Acid 10%', 'Tartaric Acid 5%', 'Citric Acid 0.5%', 'Salicylic Acid 2%', 'Sodium Hyaluronate', 'Aloe Vera', 'Aqua'],
    keyIngredients: [
      { name: 'AHA Complex 25%', benefit: 'Exfoliates surface dead skin, improves texture', icon: '⚗️' },
      { name: 'BHA (Salicylic Acid) 2%', benefit: 'Unclogs pores, treats blackheads', icon: '🔬' },
      { name: 'Hyaluronic Acid', benefit: 'Prevents over-drying during peel', icon: '💧' },
    ],
    benefits: ['Smoothens skin texture in 1 use', 'Unclogs pores and removes blackheads', 'Fades acne scars and dark spots', 'Brightens dull, tired skin', 'Clinically proven formulation'],
    skinTypes: ['Oily', 'Combination', 'Normal'],
    concerns: ['Rough texture', 'Blackheads', 'Acne scars', 'Dullness'],
    size: '30ml',
    inStock: true,
    tags: ['aha', 'bha', 'peeling', 'exfoliant', 'minimalist', 'advanced'],
  },
  {
    id: 13,
    name: 'Salicylic Acid 2% Face Wash',
    brand: 'Minimalist',
    category: 'Cleanser',
    price: 299,
    mrp: 499,
    rating: 4.6,
    reviews: 5621,
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=600&h=600&fit=crop&q=80',
    shortDesc: 'BHA face wash that clears breakouts and minimises pores with every wash.',
    description: 'A gentle, daily-use face wash with 2% Salicylic Acid (BHA) that penetrates deep into pores to remove excess oil, dead skin, and blackheads. Unlike harsh acne washes, this formula maintains skin\'s pH balance and includes soothing ingredients to prevent over-drying.',
    howToUse: 'Wet face. Apply and lather for 60 seconds. Focus on oily T-zone. Rinse with lukewarm water. Use morning and night for best results.',
    ingredients: ['Salicylic Acid 2%', 'Glycerin', 'Niacinamide 2%', 'Allantoin', 'Panthenol', 'Tea Tree Oil 0.5%', 'Sodium Laureth Sulfate', 'Aqua'],
    keyIngredients: [
      { name: 'Salicylic Acid 2%', benefit: 'Exfoliates inside pores, prevents breakouts', icon: '🧪' },
      { name: 'Tea Tree Oil', benefit: 'Antibacterial, targets acne bacteria', icon: '🌿' },
      { name: 'Niacinamide', benefit: 'Reduces post-acne redness', icon: '🔬' },
    ],
    benefits: ['Clears active breakouts', 'Unclogs and minimises pores', 'Reduces oiliness', 'Prevents future breakouts', 'Suitable for daily use'],
    skinTypes: ['Oily', 'Combination', 'Acne-prone'],
    concerns: ['Acne', 'Blackheads', 'Large pores', 'Oiliness'],
    size: '100ml',
    inStock: true,
    tags: ['acne', 'salicylic-acid', 'face-wash', 'minimalist', 'budget'],
  },
  {
    id: 14,
    name: 'Skin Brightening Kit (4 Products)',
    brand: 'DermIQ',
    category: 'Kit',
    price: 1999,
    mrp: 3296,
    rating: 4.9,
    reviews: 834,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop&q=80',
    badge: 'Save 39%',
    badgeBg: '#2D5F5A',
    shortDesc: 'Complete brightening routine: Vitamin C Serum + Niacinamide Serum + Moisturiser + SPF 50.',
    description: 'Our bestselling 4-step brightening routine curated by dermatologists. Get the Vitamin C 15% Brightening Serum, Niacinamide 10% Serum, Hyaluronic Acid Moisturiser, and Mineral SPF 50+ — everything you need for visibly brighter skin in 30 days. Save 39% vs buying individually.',
    howToUse: 'AM: Cleanse → Niacinamide Serum → Moisturiser → SPF 50. PM: Cleanse → Vitamin C Serum → Moisturiser. Use consistently for 30 days for best results.',
    ingredients: ['See individual products'],
    keyIngredients: [
      { name: 'Vitamin C 15%', benefit: 'Brightens and fades dark spots', icon: '🍊' },
      { name: 'Niacinamide 10%', benefit: 'Minimises pores, controls oil', icon: '🔬' },
      { name: 'SPF 50+ PA++++', benefit: 'Protects brightening results from UV', icon: '☀️' },
      { name: 'Hyaluronic Acid', benefit: 'Keeps skin hydrated and plump', icon: '💧' },
    ],
    benefits: ['Complete 4-step brightening routine', 'Save 39% vs buying individually', 'Dermatologist curated combination', 'Results in 30 days', 'Perfect gift for skincare lovers'],
    skinTypes: ['All skin types'],
    concerns: ['Dull skin', 'Dark spots', 'Uneven tone', 'General skincare'],
    size: '4-piece kit',
    inStock: true,
    tags: ['kit', 'brightening', 'gift', 'bundle', 'value'],
  },
]

export const getProductById = (id: number) => ALL_PRODUCTS.find(p => p.id === id)
export const getProductsByCategory = (cat: string) => ALL_PRODUCTS.filter(p => p.category === cat)
export const getProductsByBrand = (brand: string) => ALL_PRODUCTS.filter(p => p.brand === brand)

export const BESTSELLERS = ALL_PRODUCTS.filter(p => [1, 2, 3, 4, 5, 6].includes(p.id))
export const NEW_LAUNCHES = ALL_PRODUCTS.filter(p => [7, 8, 9, 10, 11, 12].includes(p.id))
export const BUDGET = ALL_PRODUCTS.filter(p => [13, 7, 9, 4, 8, 14].includes(p.id))
